opm/parser/eclipse/EclipseState/Schedule/CompletionSet.cpp, opm/parser/eclipse/EclipseState/Schedule/CompletionSet.hpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
WELOPEN minor changes:
Shut well if all completions are shut; throw exception if trying to open a well with all completions shut.
=> OPM 147: WELOPEN minor changes

opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp, opm/parser/share/keywords/000_Eclipse100/C/COMPLUMP
We do not support this keyword yet. Added exception if the keyword is used.
Fredrik Gundersen
fgun@statoil.com
=> Add complump keyword

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/EclipseState.hpp, opm/parser/eclipse/EclipseState/Tables/GasvisctTable.hpp, opm/parser/eclipse/EclipseState/Tables/OilvisctTable.hpp, opm/parser/eclipse/EclipseState/Tables/WatvisctTable.hpp, opm/parser/share/keywords/000_Eclipse100/O/OILVISCT, opm/parser/share/keywords/000_Eclipse100/W/WATVISCT, opm/parser/share/keywords/001_Eclipse300/G/GASVISCT, opm/parser/share/keywords/001_Eclipse300/O/OILVTIM
these changes are required to support temperature dependent viscosity via the "*VISCT" keywords. the additions are pretty minor. (some new keywords plus the corresponding table classes with their glue code.)
=> Temperature dependent viscosity

opm/parser/eclipse/IntegrationTests/ParseEQUIL.cpp, opm/parser/eclipse/Parser/Parser.cpp, opm/parser/eclipse/Parser/Parser.hpp
Handle decks with missing xxxxDIMS
=> Default dims

opm/parser/eclipse/IntegrationTests/IntegrationTests.cpp, opm/parser/eclipse/Parser/ParserKeyword.cpp, opm/parser/eclipse/Parser/ParserKeyword.hpp, opm/parser/eclipse/Parser/ParserRecord.cpp, opm/parser/eclipse/Parser/ParserRecord.hpp, opm/parser/eclipse/Parser/tests/ParserKeywordTests.cpp, opm/parser/eclipse/Parser/tests/ParserRecordTests.cpp
Low-level work to prepare for multi record keyword configuration.
=> Record vector

opm/parser/eclipse/OpmLog/Logger.hpp
Thanks detailed review & testing by @bska.
Would be good if @bska could test this - because it "works for me" anyway.
=> Fixed bug with iterator modification

opm/parser/eclipse/IntegrationTests/IncludeTest.cpp, opm/parser/eclipse/Parser/Parser.cpp
I'd preferred the C++11 solution but this did not compile with g++4.4.
=> Fix bug paths keyword

opm/parser/eclipse/Units/ConversionFactors.hpp, opm/parser/eclipse/Units/UnitSystem.cpp
For the METRIC and FIELD unit system.
This unit will be required in the coming development.
=> Adding unit Salinity.

debian/libopm-parser1-dev.install, debian/libopm-parser1.install
Please backport to release branch.
=> debian packaging updates

opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/DynamicStateTests.cpp
With this PR it is possible to modify the initial state/value of a DynamicState instance.
=> Dynamicstate initial

opm/parser/share/keywords/000_Eclipse100/P/PLYSHLOG
I am trying to add the keyword PLYSHLOG.  
It is my first time trying to add a keyword, and this keyword is different. 
Please suggest if anything wrong and better way to do this keyword. 
Thanks.
=> Adding keywords PLYSHLOG.

redhat/opm-parser.spec
A version bump PR will follow for release branch after this is merged and backported.
=> add redhat packaging

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/Grid/GridProperty.hpp, opm/parser/eclipse/EclipseState/Grid/tests/GridPropertyTests.cpp, opm/parser/eclipse/ert/EclKW.cpp, opm/parser/eclipse/ert/EclKW.hpp, opm/parser/eclipse/ert/FortIO.cpp, opm/parser/eclipse/ert/FortIO.hpp, opm/parser/eclipse/ert/tests/CMakeLists.txt, opm/parser/eclipse/ert/tests/test_ert_wrapper.cpp
Basic wrappers for ert types ecl_kw_type and fortio_type - might be moved to the ert library in the near future?
=> Added C++ wrappers for ERT: ecl_kw and fortio

opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp, opm/parser/eclipse/EclipseState/Schedule/Tuning.cpp, opm/parser/eclipse/EclipseState/Schedule/Tuning.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/TuningTests.cpp
Update tuning class to enable reset/set of tuning
=> Setting tuning

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp, opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp, opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
Depending on: https://github.com/Ensembles/ert/pull/783
=> Added suport for converting of Metric grid values

docs/keywords.txt
Added (some) documentation of keyword configuration.
=> Added keyword documentation

opm/parser/share/keywords/000_Eclipse100/P/PLYSHLOG, opm/parser/share/keywords/000_Eclipse100/S/SHRATE
Adding the keyword SHRATE, which should be used together with PLYSHLOG. 
The most difficult part for this keyword is that it will change the unit of the PLYSHLOG keyword. 
Please suggest how we can achieve that. Thanks.
=> Adding keyword SHRATE.

opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/EclipseState.hpp
This method will be used from opm-core wellstate
=> Added new method getNumPhases to EclipseState

docs/keywords.txt
Thanks for the improved documentation! Just a minor inclusion from me, I guess there are more than me who are familiar with XML but not with JSON, so a brief pointer might help.
=> Added information on Json for the uninformed.

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/EclipseState.hpp, opm/parser/eclipse/EclipseState/Tables/PlydhflfTable.hpp, opm/parser/eclipse/IntegrationTests/CMakeLists.txt, opm/parser/eclipse/IntegrationTests/ParsePLYDHFLF.cpp, opm/parser/share/keywords/000_Eclipse100/P/PLYDHFLF, testdata/integration_tests/POLYMER/plydhflf.data
Add a new keyword for polymer half-life degradation.
=> Add keyword PLYDHFLF.

opm/parser/eclipse/IntegrationTests/ParseVFPPROD.cpp, opm/parser/share/keywords/000_Eclipse100/V/VFPPROD
Minor changes to the test for VFP tables to test THP_VALUES and WFR_VALUES
Also changes the default of ALQ_DEF from THP (which I believe does not make sense for this item) to UNDEF.
=> Bugfixes VFPPROD and test

opm/parser/eclipse/EclipseState/Tables/PlyshlogTable.hpp, opm/parser/eclipse/IntegrationTests/ParsePLYSHLOG.cpp
correcting some copyright information. No change to the functions.
=> correcting copyright information.

opm/parser/eclipse/EclipseState/Tables/tests/TableTests.cpp
=> Fixed bug in test which checked for the wrong type of exception

opm/parser/eclipse/RawDeck/StarToken.hpp, opm/parser/eclipse/RawDeck/tests/StarTokenTests.cpp
also, extend the corresponding unit test.
this should fix #514
=> implement support for fortran-style 'd' exponent indicators

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
In #522 problems were reported when the TOPS keyword was fully specified. The code path from input deck to `struct UnstructeredGrid` is as follows:
1. Load input keywords from deck and create ert ecl_grid.
2. From the ert ecl_grid: export `ZCORN, COORD` and `ACTNUM` data.
3. In opm-core/GridManager(): create `struct UnstructeredGrid`
The problem was that when the TOPS keyword was fully specified in the input deck the bottom of cells in layer k and the top of cells in layer k + 1 were not bitwise equal, and the grid construction process would not set the cells in contact. With the current fix bitwise equality is enforced if the following condition is met:
```txt
TOPS(k) + DZ(K) =~ TOPS(k+1) 
``` 
with a precision of 1e-6.
More details can be found in: #525.
=> When fully specified TOPS agrees within 1e-6 with TOPS(k=1) and DZ: Enforce bitwise equality

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp, opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp, opm/parser/eclipse/EclipseState/Schedule/Events.cpp, opm/parser/eclipse/EclipseState/Schedule/Events.hpp, opm/parser/eclipse/EclipseState/Schedule/Group.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, opm/parser/eclipse/EclipseState/Schedule/Tuning.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.hpp, opm/parser/eclipse/EclipseState/Schedule/WellInjectionProperties.cpp, opm/parser/eclipse/EclipseState/Schedule/WellInjectionProperties.hpp, opm/parser/eclipse/EclipseState/Schedule/WellPolymerProperties.cpp, opm/parser/eclipse/EclipseState/Schedule/WellPolymerProperties.hpp, opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp, opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/CMakeLists.txt, opm/parser/eclipse/EclipseState/Schedule/tests/DynamicStateTests.cpp, opm/parser/eclipse/EclipseState/Schedule/tests/EventTests.cpp, opm/parser/eclipse/IntegrationTests/ScheduleCreateFromDeck.cpp, testdata/integration_tests/SCHEDULE/SCHEDULE_EVENTS
[ This is mainly put up as a request for comments - not yet merge ready. ]
With this PR we have created an initial system to record events from the Schedule file. The purpose of this is that you can query the events table for specific events, and then decide whether a potentially expensive calculation is required.
This is absolutely work in progress - what I would very much like feedback on are:
1. Which events are required - the current list in Events.hpp is somewhat random; and I will *not* guarantee that they are set correctly.
2. Querying for events is based on implementing `Events::operator()` - makes sense?
=> Schedule events

opm/parser/share/keywords/000_Eclipse100/M/MISC, opm/parser/share/keywords/000_Eclipse100/P/PVDS, opm/parser/share/keywords/000_Eclipse100/S/SDENSITY, opm/parser/share/keywords/000_Eclipse100/S/SGCWMIS, opm/parser/share/keywords/000_Eclipse100/S/SOLVENT, opm/parser/share/keywords/000_Eclipse100/S/SORWMIS, opm/parser/share/keywords/000_Eclipse100/S/SSFN, opm/parser/share/keywords/000_Eclipse100/S/SSOL, opm/parser/share/keywords/000_Eclipse100/W/WSOLVENT
This PR adds the necessary keywords for the solvent model
=> Add keywords for solvent model

opm/parser/eclipse/RawDeck/StarToken.hpp
=> Add <algorithm> to make it compile for gcc 4-6

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/EclipseState.hpp, opm/parser/eclipse/EclipseState/Tables/PvdsTable.hpp
-the PVDS implementation is essentially a copy of the PVDG
implementation as the PVDS table analogous the PVDG table
=> Add support for PVDS

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/EclipseState.hpp, opm/parser/eclipse/EclipseState/Tables/SsfnTable.hpp
SSFN keyword is used by the solvent model to modify the gas/solvent
saturation functions
=> Add support for SSFN

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/EclipseState.hpp, opm/parser/eclipse/EclipseState/Tables/SgfnTable.hpp, opm/parser/eclipse/EclipseState/Tables/Sof3Table.hpp
Saturation functions input using SGFN and SOF3
=> Add support for sat func family 2 keywords

opm/parser/eclipse/EclipseState/Schedule/Group.cpp
Temporary fix to get old two phase simulators to work.
=> Initialize group rates to large negative number.

opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp, opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp, opm/parser/eclipse/EclipseState/IOConfig/tests/IOConfigTest.cpp, opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp, opm/parser/eclipse/EclipseState/Schedule/tests/TimeMapTest.cpp, opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp, opm/parser/eclipse/IntegrationTests/IOConfigIntegrationTest.cpp, testdata/integration_tests/IOConfig/RPT_TEST2.DATA
- Extended IOConfig with support for RPTSOL RESTART (write of initial restart file)
- Fix for RPTRST BASIC=4/5 with frequency  
- Added IOConfig Integration test
=> Opm 217 IOConfig restart write

opm/parser/eclipse/EclipseState/Tables/VFPInjTable.cpp, opm/parser/eclipse/EclipseState/Tables/VFPProdTable.cpp
This changes a couple of superfluous throws into if-tests instead. Should have no side effects hopefully.
=> Changed throw => catch to an if test for VFP tables

opm/parser/eclipse/Deck/SCHEDULESection.cpp, opm/parser/eclipse/Deck/tests/DeckTimeStepTests.cpp, opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
This fixes a minor bug and silences some warnings.
Many of the warnings were from -Wshadow, and some pointed to real problems (readability at least) if not bugs (see the change to Schedule.cpp), I suggest including that warning by default.
=> Fix minor bug and warnings

opm/parser/share/keywords/000_Eclipse100/S/STONE1EX
that one was missing for some reason...
=> add the STONE1EX keyword

CMakeLists.txt, opm/parser/eclipse/Deck/DeckItem.hpp, opm/parser/eclipse/Deck/DeckKeyword.cpp, opm/parser/eclipse/Deck/DeckKeyword.hpp, opm/parser/eclipse/Deck/DeckRecord.cpp, opm/parser/eclipse/Deck/DeckRecord.hpp, opm/parser/eclipse/Deck/DeckStringItem.cpp, opm/parser/eclipse/Deck/DeckStringItem.hpp, opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/Generator/KeywordLoader.cpp, opm/parser/eclipse/Parser/createDefaultKeywordList.cpp, opm/parser/share/keywords/000_Eclipse100/E/ENDSKIP, opm/parser/share/keywords/000_Eclipse100/R/RPTRUNSP, opm/parser/share/keywords/000_Eclipse100/S/SKIP, opm/parser/share/keywords/000_Eclipse100/S/SKIP100, opm/parser/share/keywords/000_Eclipse100/S/SKIP300, opm/parser/share/keywords/000_Eclipse100/S/SPECHEAT, opm/parser/share/keywords/000_Eclipse100/S/SPECROCK, opm/parser/share/keywords/000_Eclipse100/T/THCONR, opm/parser/share/keywords/000_Eclipse100/W/WTEMP, opm/parser/share/keywords/001_Eclipse300/B/BLOCK_PROBE300
Some minor updates here and there ....
=> Minor stuff

opm/parser/eclipse/Applications/opm-eclkw.cpp, opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp, opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp, opm/parser/eclipse/EclipseState/SimulationConfig/tests/SimulationConfigTest.cpp, opm/parser/eclipse/Parser/ParserKeyword.cpp, opm/parser/eclipse/Parser/ParserKeyword.hpp, opm/parser/eclipse/Parser/tests/ParserKeywordTests.cpp, opm/parser/eclipse/Parser/tests/ParserTests.cpp, opm/parser/share/keywords/000_Eclipse100/C/CPR
Also Allowed parser keywords without items
=> Added CPR keyword

opm/parser/eclipse/EclipseState/Tables/PlymaxTable.hpp, opm/parser/eclipse/EclipseState/Tables/PlyrockTable.hpp, opm/parser/eclipse/EclipseState/Tables/TableManager.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.hpp, opm/parser/eclipse/EclipseState/Tables/tests/TableManagerTests.cpp, opm/parser/eclipse/IntegrationTests/CMakeLists.txt, opm/parser/eclipse/IntegrationTests/Polymer.cpp, testdata/integration_tests/POLYMER/POLY.inc
Fixing regressions with PLYMAX and PLYROCK tables.
=> Plymax bug

opm/parser/eclipse/Deck/Section.hpp, opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp, opm/parser/eclipse/EclipseState/SimulationConfig/tests/SimulationConfigTest.cpp, opm/parser/share/keywords/000_Eclipse100/C/CONNECTION_PROBE, opm/parser/share/keywords/000_Eclipse100/C/CPR
The CPR keyword can appear both in the SUMMARY section and the RUNSPEC section, with completely different meaning. We just barely manage to get around this without introducing section aware keywords.
=> Cpr support

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/Deck/tests/DeckRecordTests.cpp, opm/parser/eclipse/Parser/ParseMode.cpp, opm/parser/eclipse/Parser/ParseMode.hpp, opm/parser/eclipse/Parser/Parser.cpp, opm/parser/eclipse/Parser/ParserKeyword.cpp, opm/parser/eclipse/Parser/ParserKeyword.hpp, opm/parser/eclipse/Parser/ParserRecord.cpp, opm/parser/eclipse/Parser/ParserRecord.hpp, opm/parser/eclipse/Parser/tests/ParseModeTests.cpp, opm/parser/eclipse/Parser/tests/ParserKeywordTests.cpp, opm/parser/eclipse/Parser/tests/ParserRecordTests.cpp
Extra elements in the input record are handled with
ParseMode::handleError() with the new error mode PARSE_EXTRA_DATA.
=> ParseMode::PARSE_EXTRA_DATA

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/Tables/tests/TableManagerTests.cpp, opm/parser/eclipse/EclipseState/Util/RecordVector.hpp, opm/parser/eclipse/EclipseState/Util/tests/CMakeLists.txt, opm/parser/eclipse/EclipseState/Util/tests/RecordVectorTests.cpp, opm/parser/eclipse/Parser/ParserKeyword.hpp
More funny keyword structure coming - this is a preparation.
=> Renamed ElasticVector -> RecordVector

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp, opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp, opm/parser/eclipse/EclipseState/Grid/PinchMode.cpp, opm/parser/eclipse/EclipseState/Grid/PinchMode.hpp
Add support for pinchout option and multz option.
=> Add support for PINCH item 4 and 5.

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/Tables/SgwfnTable.hpp, opm/parser/eclipse/EclipseState/Tables/TableManager.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.hpp, opm/parser/eclipse/EclipseState/Tables/tests/TableManagerTests.cpp, opm/parser/share/keywords/000_Eclipse100/S/SGWFN
This keyword belongs to saturation function family II, even it's just for gas-water system, but this can be  useful for other respect, like relperm diagnosis.
=> Add keyword SGWFN.

opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
=> Make dist() call well-defined.

redhat/opm-parser.spec
=> update redhat packaging

opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.hpp, opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp, opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp, opm/parser/eclipse/EclipseState/Schedule/tests/WellPropertiesTests.cpp
See: #619 
Have removed the test of BHP limit behavior when the well changes injector <-> producer; as the expected behavior was not really clear here.
=> Hwells bhplimit

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/Schedule/DynamicVector.hpp, opm/parser/eclipse/EclipseState/Schedule/Events.cpp, opm/parser/eclipse/EclipseState/Schedule/Events.hpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/CMakeLists.txt, opm/parser/eclipse/EclipseState/Schedule/tests/DynamicVectorTests.cpp, opm/parser/eclipse/EclipseState/Schedule/tests/EventTests.cpp
Created a vector<T> class coupled to a TimeMap - first babystep towards supporting MULTFLT++ in Schedule section.
=> Dynamic vector

opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
This mimics behaviour observed from Eclipse results on the new model.
=> Prevent wells with zero rate and crossflow disabled to open

opm/parser/eclipse/Deck/DeckKeyword.hpp, opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/EclipseState.hpp, opm/parser/eclipse/EclipseState/Grid/TransMult.cpp, opm/parser/eclipse/EclipseState/Grid/TransMult.hpp, opm/parser/eclipse/EclipseState/Schedule/DynamicVector.hpp, opm/parser/eclipse/EclipseState/Schedule/Events.cpp, opm/parser/eclipse/EclipseState/Schedule/Events.hpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/CMakeLists.txt, opm/parser/eclipse/EclipseState/Schedule/tests/DynamicVectorTests.cpp, opm/parser/eclipse/EclipseState/Schedule/tests/EventTests.cpp, opm/parser/eclipse/EclipseState/Schedule/tests/GeomodifierTests.cpp, opm/parser/eclipse/EclipseState/Util/OrderedMap.hpp, opm/parser/eclipse/IntegrationTests/CMakeLists.txt, opm/parser/eclipse/IntegrationTests/TransMultIntegrationTests.cpp, opm/parser/eclipse/Parser/tests/ParseModeTests.cpp, testdata/integration_tests/TRANS/Deck1
Store small per-timestep 'minideck' for Schedule modifiers. With this PR the parser part of support for MULTFLT in Schedule section should be complete.
=> Geo mini deck

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp, opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.hpp, opm/parser/eclipse/EclipseState/Schedule/Segment.cpp, opm/parser/eclipse/EclipseState/Schedule/Segment.hpp, opm/parser/eclipse/EclipseState/Schedule/SegmentSet.cpp, opm/parser/eclipse/EclipseState/Schedule/SegmentSet.hpp, opm/parser/eclipse/EclipseState/Schedule/Well.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.hpp, opm/parser/eclipse/IntegrationTests/CMakeLists.txt, opm/parser/eclipse/IntegrationTests/ParseMULTSEGWELL.cpp, testdata/integration_tests/SCHEDULE/SCHEDULE_MULTISEGMENT_WELL
which is split from the PR #615 manually. 
Many of the comments PR #615 have been addressed, while not all of them yet. 
I hope the new PR is easier to review.
=> Support for the keyword WELSEGS

opm/parser/eclipse/IntegrationTests/ParseMULTSEGWELL.cpp, opm/parser/eclipse/IntegrationTests/ParseSLGOF.cpp
As usual I get a few more warnings than most...
=> Silence warnings from boost.

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/Tables/MiscTable.hpp, opm/parser/eclipse/EclipseState/Tables/MsfnTable.hpp, opm/parser/eclipse/EclipseState/Tables/PmiscTable.hpp, opm/parser/eclipse/EclipseState/Tables/SgcwmisTable.hpp, opm/parser/eclipse/EclipseState/Tables/SimpleTable.cpp, opm/parser/eclipse/EclipseState/Tables/SimpleTable.hpp, opm/parser/eclipse/EclipseState/Tables/SorwmisTable.hpp, opm/parser/eclipse/EclipseState/Tables/TableManager.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.hpp, opm/parser/eclipse/IntegrationTests/CMakeLists.txt, opm/parser/eclipse/IntegrationTests/ParseMiscible.cpp, opm/parser/share/keywords/000_Eclipse100/M/MSFN, opm/parser/share/keywords/000_Eclipse100/P/PMISC
Add table support for the following keywords
MSFN
PMISC
MISC
SGCWMIS
SORWMIS
Also checkRange() is added to SimpleTable to check whether the input span [0,1]
=> Miscible keywords

opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
Add missing methods for MSFN, PMISC, MISC, SGCWMIS and SORWMIS
=> Add missing methods in TableManager.cpp

opm/parser/eclipse/EclipseState/Grid/NNC.cpp, opm/parser/eclipse/EclipseState/Grid/NNC.hpp, opm/parser/eclipse/IntegrationTests/NNCTests.cpp
Adds 
- default constructor
- non-const access of the nncs
- test
=> Support for minpv-pinch-nnc 

opm/parser/eclipse/EclipseState/Schedule/Group.cpp, opm/parser/eclipse/EclipseState/Schedule/Group.hpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp, opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/GroupTests.cpp, opm/parser/share/keywords/000_Eclipse100/G/GEFAC
- Added and internalized GEFAC keyword
- Added support for WCONPROD controlmode option "GRUP"
=> Internalized GEFAC keyword, added support for WCONPROD controlmode option GRUP

.travis.yml, README.md, travis/build-and-test-opm-parser.sh, travis/build-opm-parser.sh, travis/clone-and-build-ert.sh
Adds a `travis` folder with scripts for building and testing **opm-parser** + building dependencies
=> Updated TravisCI integration

opm/parser/eclipse/Deck/Deck.hpp, opm/parser/eclipse/Deck/DeckStringItem.hpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp, opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/WellPropertiesTests.cpp, opm/parser/eclipse/IntegrationTests/ParseTOPS.cpp, opm/parser/eclipse/OpmLog/Logger.hpp
This is a minor fixup of: #681; the last commit has been ammended to.
=> Atgeirr fix minor issues

opm/parser/eclipse/Deck/Deck.cpp, opm/parser/eclipse/Deck/DeckItem.cpp, opm/parser/eclipse/EclipseState/Summary/Summary.cpp, opm/parser/eclipse/Parser/ParserDoubleItem.hpp, opm/parser/eclipse/Parser/ParserIntItem.hpp, opm/parser/eclipse/Parser/ParserStringItem.hpp
Restores compilation on my platform (missing includes) and makes it warning-free.
=> Minor fix and warnings.

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/Summary/Summary.cpp, opm/parser/eclipse/Utility/Functional.cpp, opm/parser/eclipse/Utility/Functional.hpp, opm/parser/eclipse/Utility/tests/CMakeLists.txt, opm/parser/eclipse/Utility/tests/FunctionalTests.cpp
Utility/Functional is a lightweight high level functional-oriented sub library that attempts to abstract some common uses and boilerplate around the parser code (and later maybe for other modules to use).
This patch introduce only three functions, but they have proven common enough to warrant some common implementation.
I plan for things here to be added on a by-need basis.
=> Introduce Utility/Functional

opm/parser/eclipse/OpmLog/OpmLog.cpp, opm/parser/eclipse/OpmLog/OpmLog.hpp
Add some more functions and members for OpmLog for further work,
=> More function opmlog

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/OpmLog/EclipsePRTLog.cpp, opm/parser/eclipse/OpmLog/EclipsePRTLog.hpp
This PR intend to add a prototype for output eclipse PRT file, more usefule functions could be added later.
=> Add EclipsePRTLog backend.

opm/parser/eclipse/RawDeck/RawRecord.hpp, opm/parser/eclipse/RawDeck/StarToken.cpp, opm/parser/eclipse/Utility/Stringview.cpp, opm/parser/eclipse/Utility/Stringview.hpp
This fixes a few bugs that prevented compilation and caused test failures.
=> Some minor fixes

opm/parser/eclipse/EclipseState/Tables/Tables.cpp
This should fix: https://github.com/OPM/opm-parser/issues/716
=> PLYVISC: INCREASING instead of STRIVLY_INCREASING.

opm/parser/share/keywords/000_Eclipse100/A/AQUDIMS, opm/parser/share/keywords/000_Eclipse100/M/MEMORY, opm/parser/share/keywords/000_Eclipse100/P/PARALLEL
=> Added 3 keywords

opm/parser/eclipse/Deck/DeckItem.cpp, opm/parser/eclipse/Deck/DeckItem.hpp, opm/parser/eclipse/Deck/tests/DeckRecordTests.cpp, opm/parser/eclipse/Parser/Parser.cpp, opm/parser/eclipse/Parser/ParserDoubleItem.cpp, opm/parser/eclipse/Parser/ParserDoubleItem.hpp, opm/parser/eclipse/Parser/ParserIntItem.cpp, opm/parser/eclipse/Parser/ParserIntItem.hpp, opm/parser/eclipse/Parser/ParserItem.hpp, opm/parser/eclipse/Parser/ParserKeyword.cpp, opm/parser/eclipse/Parser/ParserKeyword.hpp, opm/parser/eclipse/Parser/ParserRecord.cpp, opm/parser/eclipse/Parser/ParserRecord.hpp, opm/parser/eclipse/Parser/ParserStringItem.cpp, opm/parser/eclipse/Parser/ParserStringItem.hpp, opm/parser/eclipse/Parser/tests/ParserItemTests.cpp, opm/parser/eclipse/Parser/tests/ParserRecordTests.cpp, opm/parser/eclipse/RawDeck/RawKeyword.cpp, opm/parser/eclipse/RawDeck/RawKeyword.hpp, opm/parser/eclipse/RawDeck/RawRecord.cpp, opm/parser/eclipse/RawDeck/RawRecord.hpp, opm/parser/eclipse/RawDeck/tests/RawKeywordTests.cpp
A handful of minor performance enhancements and small refactors. Doesn't affect anything externally but runtime.
=> Various improvements

opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp, opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp, opm/parser/eclipse/EclipseState/IOConfig/tests/IOConfigTest.cpp, opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp, opm/parser/eclipse/EclipseState/Schedule/Well.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/DynamicStateTests.cpp, opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp, opm/parser/eclipse/IntegrationTests/IOConfigIntegrationTest.cpp
Interernalize the first output step where RFT / Restart output is requested. In particular for RFT this information will be used to speed up the RFT output.
=> First output step

opm/parser/eclipse/Parser/ParseContext.cpp, opm/parser/eclipse/Parser/ParseContext.hpp
add MessageContainer to ParseContext.
=> add member and functions.

opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/Grid/GridPropertyInitializers.cpp, opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
Fixes compile error due to missing includes and silences some warnings.
=> Minor fixes

opm/parser/eclipse/Deck/Deck.cpp, opm/parser/eclipse/Deck/Deck.hpp, opm/parser/eclipse/Deck/DeckItem.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.cpp, opm/parser/eclipse/EclipseState/Tables/VFPInjTable.cpp, opm/parser/eclipse/EclipseState/Tables/VFPInjTable.hpp, opm/parser/eclipse/EclipseState/Tables/VFPProdTable.cpp, opm/parser/eclipse/EclipseState/Tables/VFPProdTable.hpp, opm/parser/eclipse/Parser/Parser.cpp, opm/parser/eclipse/Parser/ParserKeyword.cpp, opm/parser/eclipse/Parser/ParserKeyword.hpp, opm/parser/eclipse/Parser/ParserRecord.cpp, opm/parser/eclipse/Parser/ParserRecord.hpp
Removes uses of const_cast in methods that lead to possibly undefined behaviour.
=> Remove possible undefined const cast

jenkins/build-opm-parser.sh
ref https://github.com/OPM/opm-simulators/issues/643
do let me test run it before merge.
=> pass OPM_DATA_ROOT in jenkins builds

opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp, opm/parser/eclipse/EclipseState/Grid/GridPropertyInitializers.cpp, opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp, opm/parser/eclipse/EclipseState/SimulationConfig/tests/ThresholdPressureTest.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.hpp, opm/parser/eclipse/Parser/tests/MessageContainerTest.cpp
With this opm-parser compiles for me with no warnings again.
=> Silence warnings

opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp, opm/parser/eclipse/EclipseState/Grid/tests/ADDREGTests.cpp, opm/parser/eclipse/EclipseState/Grid/tests/CopyRegTests.cpp, opm/parser/eclipse/EclipseState/Grid/tests/EqualRegTests.cpp, opm/parser/eclipse/EclipseState/Grid/tests/GridPropertiesTests.cpp, opm/parser/eclipse/EclipseState/Grid/tests/GridPropertyTests.cpp, opm/parser/eclipse/EclipseState/Grid/tests/MULTREGTScannerTests.cpp, opm/parser/eclipse/EclipseState/Grid/tests/MultiRegTests.cpp, opm/parser/eclipse/EclipseState/Grid/tests/PORVTests.cpp, opm/parser/eclipse/EclipseState/Grid/tests/SatfuncPropertyInitializersTests.cpp, opm/parser/eclipse/EclipseState/tests/CMakeLists.txt, opm/parser/eclipse/EclipseState/tests/Eclipse3DPropertiesTests.cpp, opm/parser/eclipse/Parser/tests/MessageContainerTest.cpp
* Added Eclipse3DPropertiesTests
* Refactored tests to use Eclipse3DProperties instead of EclipseState
* Added unsigned literal to MessageContainerTest
=> Testing Eclipse3DProperties API

opm/parser/eclipse/EclipseState/Schedule/CompletionSet.hpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp, opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp, opm/parser/eclipse/EclipseState/Summary/Summary.cpp, opm/parser/eclipse/EclipseState/Summary/tests/SummaryTests.cpp
Internalise and generate `smspec_node` for the Region and Completion family of keywords.
=> New summary keywords

opm/parser/eclipse/EclipseState/Summary/Summary.cpp
Can switch back when we move to C++14 uniformly.
=> Silence missing-braces warning.

opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
Reported by Bård Skaflestad in
https://github.com/OPM/opm-parser/issues/774.
=> Fix off-by-one error in satfuncinit.

opm/parser/eclipse/EclipseState/Schedule/Group.cpp, opm/parser/eclipse/EclipseState/Schedule/Group.hpp, opm/parser/eclipse/EclipseState/Schedule/WellSet.cpp, opm/parser/eclipse/EclipseState/Schedule/WellSet.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/GroupTests.cpp, opm/parser/eclipse/EclipseState/Schedule/tests/WellSetTests.cpp
Add support for querying what wells are in a given group at a certain
time step.
=> Adds Group::getWells method

CMakeLists.txt
Make sure CXX_FLAGS are passed on. 
Should I fetch one of my brown paper bags? Comments from e.g @akva2 or other build specialists welcome.
=> Ensure that CMAKE_CXX_FLAGS are propagated.

opm/parser/eclipse/Deck/tests/DeckRecordTests.cpp, opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp, opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp, opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp, opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.hpp, opm/parser/eclipse/EclipseState/SimulationConfig/tests/SimulationConfigTest.cpp, opm/parser/eclipse/EclipseState/SimulationConfig/tests/ThresholdPressureTest.cpp, opm/parser/eclipse/Parser/ParseContext.cpp, opm/parser/eclipse/Parser/ParseContext.hpp, opm/parser/eclipse/Parser/Parser.cpp, opm/parser/eclipse/Parser/ParserKeyword.cpp, opm/parser/eclipse/Parser/ParserKeyword.hpp, opm/parser/eclipse/Parser/ParserRecord.cpp, opm/parser/eclipse/Parser/ParserRecord.hpp, opm/parser/eclipse/Parser/tests/ParserKeywordTests.cpp, opm/parser/eclipse/Parser/tests/ParserRecordTests.cpp
See: https://github.com/OPM/opm-parser/pull/794
Pure git changes:
1. Rebased to get rid of the merge commit,
2. Squashed the two last commits
=> Ming log more messages

opm/parser/eclipse/Parser/Parser.cpp
Save some implementation by using std::stack as interface and
implementation for InputStack. Remove the vector pair of file and file*
and just use file directly.
=> Implement InputStack with std::stack

opm/parser/eclipse/Parser/MessageContainer.cpp, opm/parser/eclipse/Parser/MessageContainer.hpp, opm/parser/eclipse/Parser/tests/MessageContainerTest.cpp
See https://github.com/OPM/opm-common/pull/135
=> Add Prtinfo message type allows messages go into print file.

opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.hpp, opm/parser/eclipse/EclipseState/Tables/VFPProdTable.cpp, opm/parser/eclipse/EclipseState/Tables/VFPProdTable.hpp
- Make a much more clear messages for VFP
- Log the history related message to print file.
=> Log well messages

opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
Double check that these messages eclipse print in the terminal, but for the second model, this kind of messages are too much, maybe let it go into print file first is a good choice.
=> Well related messages should have type MessageType::note

opm/parser/eclipse/EclipseState/Tables/VFPProdTable.cpp
1. If the message is more than one line, add "\n" to the end.
2. apply "msg + file name + line number"  format.
=> minor format improvement

opm/parser/eclipse/RawDeck/RawKeyword.cpp, opm/parser/eclipse/Utility/String.hpp, opm/parser/eclipse/Utility/tests/CMakeLists.txt, opm/parser/eclipse/Utility/tests/StringTests.cpp
An entry point for string-related tools and operations.
=> String tools

opm/parser/eclipse/Parser/tests/ParseContextTests.cpp, opm/parser/share/keywords/000_Eclipse100/O/OPERATE
Will parse - *not* internalize - the `OPERATE` keyword.
=> Added keyword OPERATE.

opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp, opm/parser/eclipse/EclipseState/EclipseConfig.cpp, opm/parser/eclipse/EclipseState/EclipseConfig.hpp, opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/Grid/GridProperties.cpp, opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
=> Suppress warnings

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp, opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
Micro step towards proper EclipseGrid representation of the simulation grid.
=> Cornerpoint based EclipseGrid constructor.

opm/parser/share/keywords/000_Eclipse100/W/WECON
A mere compilation test showed the failure here.
Repeat after me: I WILL NEVER EVER PULL UNTESTED CODE INTO A PRODUCTION GIT.  Now go repeat it 10000 times bart simpson style until it sticks.
=> fixed: broken keyword in e576f399f18da63172aa983d3f630e05111e2b0d

opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp, opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp, opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
=> Expands ALL keyword for summary

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp, opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp, opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
For *now* mainly for testing of the output writer.
=> Added EclipseGrid::getActiveMap().

opm/parser/eclipse/EclipseState/EclipseConfig.cpp, opm/parser/eclipse/EclipseState/EclipseConfig.hpp, opm/parser/eclipse/EclipseState/EclipseState.cpp, opm/parser/eclipse/EclipseState/EclipseState.hpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp, opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp, opm/parser/eclipse/EclipseState/Schedule/tests/TimeMapTest.cpp, opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp, opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp, opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp, opm/parser/eclipse/IntegrationTests/IOConfigIntegrationTest.cpp, opm/parser/eclipse/Parser/ParseContext.cpp, opm/parser/eclipse/Parser/ParseContext.hpp, testdata/integration_tests/IOConfig/SPE9_END.DATA
Downstream: 
opm-output: https://github.com/OPM/opm-output/pull/54
~~opm-data: https://github.com/OPM/opm-data/pull/112~~
=> TimeMap bug for RPTRST BASIC=4 terminated before a year!

opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
=> Fix compile issue.

opm/parser/eclipse/Deck/Deck.cpp
Fixup of some messy constructors.
This is very minor and I'll merge as soon as travis is happy, as nothing should be affected by this. Just some prettification.
=> Syntactic cleanup

opm/parser/eclipse/Applications/opmi.cpp
=> Removed OpmLog from opmi.

opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp, opm/parser/eclipse/EclipseState/IOConfig/tests/RestartConfigTests.cpp
Discovered by compiler warning.
=> Remove two unused functions.

jenkins/build-opm-parser.sh, jenkins/build-pr.sh, jenkins/build.sh
Depends on https://github.com/OPM/opm-common/pull/168
=> simply jenkins scripts after ert reorganization

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp, opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
Simplify slightly by using automatic memory management, rather than
heap-alloc.
=> Active cell cache with automatic storage

opm/parser/eclipse/EclipseState/Grid/GridProperty.cpp, opm/parser/eclipse/EclipseState/Grid/GridProperty.hpp, opm/parser/eclipse/EclipseState/Grid/tests/GridPropertyTests.cpp
Convenience functionality for region calculations.
=> Scan a property and return cells equal to a value.

opm/parser/eclipse/EclipseState/checkDeck.cpp, opm/parser/eclipse/Parser/Parser.cpp
I'm not sure why this was wrong, probably due to the carelessness....
see https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/Parser/MessageContainer.hpp#L77
=> Argument of warning() method is msg, filename, linenumber.

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp, opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp, opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
Will create an EclipseGrid copy where zcorn and zctnum have been adjusted.
Depends on: https://github.com/Ensembles/ert/pull/1217
=> WIP: Added EclipseGrid processed copy.

opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp, opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.hpp
Should not have any bad impact to other parts of OPM.
=> adding FLD to the ControlEnum of GroupProduction

opm/parser/eclipse/python/CMakeLists.txt, opm/parser/eclipse/python/cmake/python.cmake, opm/parser/eclipse/python/python/opm/__init__.py, opm/parser/eclipse/python/python/opm/deck/deck.py, opm/parser/eclipse/python/python/opm/deck/deck_item.py, opm/parser/eclipse/python/python/opm/deck/deck_keyword.py, opm/parser/eclipse/python/python/opm/deck/deck_record.py, opm/parser/eclipse/python/python/opm/deck/item_type_enum.py, opm/parser/eclipse/python/python/opm/ecl_state/grid/eclipse_grid.py, opm/parser/eclipse/python/python/opm/ecl_state/schedule/schedule.py, opm/parser/eclipse/python/python/opm/ecl_state/tables/table.py, opm/parser/eclipse/python/python/opm/ecl_state/tables/table_index.py, opm/parser/eclipse/python/python/opm/ecl_state/tables/table_manager.py, opm/parser/eclipse/python/python/opm/parser/error_action.py, opm/parser/eclipse/python/python/opm/parser/parse_context.py, opm/parser/eclipse/python/python/opm/parser/parser.py
This PR is the result of running sed on `s/ert.cwrap/cwrap/g`.
It reflects the upcoming changes in ert (see [ert#1159](https://github.com/Ensembles/ert/pull/1159)).
Depends on
* Ensembles/ert#1159
* Opm/opm-common#181
=> Use cwrap library from ert

redhat/opm-parser.spec
=> update redhat6 packaging

opm/parser/eclipse/Deck/DeckItem.cpp, opm/parser/eclipse/Deck/DeckItem.hpp, opm/parser/eclipse/python/c_inter/cdeck_item.cc
typeof is a semi-reserved symbol in gcc (gcc extension to get typeid)
=> changed: rename function getType

opm/parser/eclipse/RawDeck/RawConsts.hpp
Just relying on the char data type is not sufficient to guard against
overflows, and several input decks would invoke undefined behaviour.
This code path is extremely hot, so bit-wise checking for overflow is
done over a two-branch check.
=> Check for separator/quote table overflow

opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
=> Reference MessageLimit functions.

opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp, opm/parser/eclipse/EclipseState/Tables/SimpleTable.cpp, opm/parser/eclipse/EclipseState/Tables/TableColumn.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
* Implemented missing method "name" in TableColumn.cpp
* add inline to method in RestartConfig to remove warning
* Whitespace changes
=> Minor fixes unrelated (warnings etc)

opm/parser/eclipse/EclipseState/Tables/PvtxTable.cpp, opm/parser/eclipse/EclipseState/Tables/PvtxTable.hpp, opm/parser/eclipse/EclipseState/Tables/tests/PvtxTableTests.cpp
Small thing to support output of PVT tables.
=> Added inner table iterators to PvtxTable.

opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp, opm/parser/eclipse/EclipseState/Runspec.cpp, opm/parser/eclipse/EclipseState/Runspec.hpp, opm/parser/eclipse/EclipseState/Tables/Tabdims.hpp, opm/parser/eclipse/EclipseState/Tables/TableManager.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.hpp, opm/parser/eclipse/EclipseState/Tables/tests/TabdimsTests.cpp, opm/parser/eclipse/EclipseState/Tables/tests/TableManagerTests.cpp, opm/parser/eclipse/EclipseState/tests/RunspecTests.cpp
1. Removed Tabdims(int,int,int, ....) constructor and added
Tabdims(Deck) constructor.
2. Added Tabdims member to Runspec( ) object.
3. Changed std_shared_ptr<Tabdims> to Tabdims member in TableManager.
=> Changes in Tabdims construction:

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp, opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp, opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
=> Added functionality to "fix" ZCORN problems.

changelog.md
It's when you write a changelog you actually realise how much we've actually done since October. Nice work!
=> Changelog for November 2016

opm/parser/eclipse/EclipseState/Schedule/Well.cpp, opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
Fixes a bug where completions specified after a record just updated a
completion would be assigned a too high completion number.
COMPDAT can be used to re-specify some properties of connections, in
which case they're not actually new completions and the completion
number shouldn't change.
=> Only increment complnum when a completion is new

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp, opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp, opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
In #990 we adjust the ZCORN values if a cell is twisted. With this PR we also adjust the ZCORN values if the z values of two cells come out of order.
=> ZCORN adjustments considers cell-cell relation.

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/Tables/PvtwTable.hpp, opm/parser/eclipse/EclipseState/Tables/PvtxTable.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.hpp, opm/parser/eclipse/EclipseState/Tables/tests/PvtxTableTests.cpp
Provide a richer interface to read the PVTW table.
=> TableManager.getPvtwTable

changelog.md
=> Changelog December 2016

opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, opm/parser/eclipse/EclipseState/Tables/FlatTable.hpp, opm/parser/eclipse/EclipseState/Tables/TableManager.cpp, opm/parser/eclipse/EclipseState/Tables/TableManager.hpp, opm/parser/eclipse/EclipseState/Tables/Tables.cpp, opm/parser/eclipse/EclipseState/Tables/tests/TableManagerTests.cpp
=> Understand PVCDO, VISCREF, WATDENT

opm/parser/eclipse/CMakeLists.txt, opm/parser/eclipse/EclipseState/EndpointScaling.cpp, opm/parser/eclipse/EclipseState/Runspec.cpp, opm/parser/eclipse/EclipseState/Runspec.hpp, opm/parser/eclipse/EclipseState/tests/RunspecTests.cpp, opm/parser/eclipse/Utility/String.hpp
Understand and expose the ENDSCALE keyword.
=> Endpoint scaling support

opm/parser/share/keywords/000_Eclipse100/F/FIPOWG, opm/parser/share/keywords/000_Eclipse100/O/OPERNUM, opm/parser/share/keywords/000_Eclipse100/W/WELL_PROBE
ps., are anyone familiar with `FIPREG`?
=> Added JSON for FIPOWG

opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp, opm/parser/eclipse/EclipseState/Runspec.cpp, opm/parser/eclipse/EclipseState/Runspec.hpp, opm/parser/eclipse/EclipseState/tests/RunspecTests.cpp, opm/parser/eclipse/Units/UnitSystem.cpp, opm/parser/eclipse/Units/UnitSystem.hpp, opm/parser/eclipse/Units/tests/UnitTests.cpp
=> Added method Runspec::eclPhaseMask( )

opm/parser/eclipse/python/c_inter/CMakeLists.txt, opm/parser/eclipse/python/c_inter/cecl_props.cc, opm/parser/eclipse/python/python/opm/ecl_state/grid/CMakeLists.txt, opm/parser/eclipse/python/python/opm/ecl_state/grid/__init__.py, opm/parser/eclipse/python/python/opm/ecl_state/grid/ecl_props.py, opm/parser/eclipse/python/tests/ecl_state/grid/CMakeLists.txt, opm/parser/eclipse/python/tests/ecl_state/grid/test_props.py, testdata/integration_tests/GRID/CORNERPOINT_ACTNUM.DATA
Very basic python support; this might very well be removed - just to smooth the way in for #1040
=> Added very basic Eclipse3DProperties in Python.

opm/parser/eclipse/python/c_inter/cschedule.cc, opm/parser/eclipse/python/python/opm/ecl_state/grid/ecl_props.py, opm/parser/eclipse/python/python/opm/ecl_state/schedule/schedule.py, opm/parser/eclipse/python/tests/ecl_state/schedule/test_schedule.py
=> Minor python fixup.

opm/parser/eclipse/EclipseState/Schedule/Events.hpp, opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.cpp, opm/parser/eclipse/EclipseState/Schedule/Well.hpp, opm/parser/eclipse/IntegrationTests/ScheduleCreateFromDeck.cpp
=> Well events

lib/eclipse/CMakeLists.txt, lib/eclipse/IntegrationTests/CMakeLists.txt
up/down/sidestream of https://github.com/OPM/opm-data/pull/217
=> update path due to opm-data restructuring

lib/eclipse/CMakeLists.txt, lib/eclipse/IntegrationTests/CMakeLists.txt
Up/side/down stream of https://github.com/OPM/opm-data/pull/223
=> adjust for changed opm-data path

lib/eclipse/EclipseState/Runspec.cpp, lib/eclipse/EclipseState/Schedule/Well.cpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/Runspec.hpp, lib/eclipse/tests/RunspecTests.cpp
Also add test for solvent in RunspecTests.
=> Add polymer to phase class in Runspec

lib/eclipse/tests/Eclipse3DPropertiesTests.cpp
Mostly for completeness since the underlying implementation just piggy-backs on the existing support for Cartesian tensors.
This should really have been part of #1094.  My apologies for not thinking of this sooner.
=> 3D Properties Test: Check Radial Tensor Support

lib/eclipse/EclipseState/Grid/GridProperty.cpp, lib/eclipse/EclipseState/Tables/TableManager.cpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/Tables/TableManager.hpp, lib/eclipse/share/keywords/000_Eclipse100/R/RTEMP, lib/eclipse/share/keywords/000_Eclipse100/R/RTEMPA, lib/eclipse/share/keywords/keyword_list.cmake, lib/eclipse/tests/Eclipse3DPropertiesTests.cpp
Initialize TEMPI property from the `RTEMP` keyword.
See: https://github.com/OPM/opm-simulators/issues/1231
=> Tempi init

lib/eclipse/EclipseState/Schedule/Tuning.cpp
Necessary to fix compile on my system.
=> Add missing <string> include.

debian/control, debian/libopm-parser1-dev.install
Plus some changes due to the new build system.
=> update packaging to reflect ecl rebranding

lib/eclipse/share/keywords/000_Eclipse100/A/ACTION, lib/eclipse/share/keywords/000_Eclipse100/A/APIGROUP, lib/eclipse/share/keywords/000_Eclipse100/E/ENDACTIO, lib/eclipse/share/keywords/000_Eclipse100/G/GLIFTOPT, lib/eclipse/share/keywords/000_Eclipse100/G/GSATPROD, lib/eclipse/share/keywords/000_Eclipse100/L/LIFTOPT, lib/eclipse/share/keywords/000_Eclipse100/N/NOWARN, lib/eclipse/share/keywords/000_Eclipse100/P/PPCWMAX, lib/eclipse/share/keywords/000_Eclipse100/Q/QDRILL, lib/eclipse/share/keywords/000_Eclipse100/W/WARN, lib/eclipse/share/keywords/000_Eclipse100/W/WELPI, lib/eclipse/share/keywords/000_Eclipse100/W/WGASPROD, lib/eclipse/share/keywords/000_Eclipse100/W/WINJMULT, lib/eclipse/share/keywords/000_Eclipse100/W/WLIMTOL, lib/eclipse/share/keywords/000_Eclipse100/W/WORKTHP, lib/eclipse/share/keywords/keyword_list.cmake
Added deck support for the following keywords
ACTION,
APIGROUP,
ENDACTIO,
GLIFTOPT,
GSATPROD,
LIFTOPT,
NOWARN,
PPCWMAX,
QDRILL,
WARN,
WELPI,
WGASPROD,
WINJMULT,
WLIMTOL,
WORKTHP
=> Added deck support for several keywords

lib/eclipse/EclipseState/Grid/TransMult.cpp, lib/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
Fixes two more minor warnings (init order and unused function).
=> Silence minor warnings.

lib/eclipse/share/keywords/000_Eclipse100/A/AQUCT, lib/eclipse/share/keywords/000_Eclipse100/A/AQUTAB, lib/eclipse/share/keywords/000_Eclipse100/O/OPERATER, lib/eclipse/share/keywords/000_Eclipse100/R/RSCONST, lib/eclipse/share/keywords/keyword_list.cmake
Added parser support for the following keywords:
AQUCT
AQUTAB
RSCONST
OPERATER
=> New keywords

applications/opmi.cpp, lib/eclipse/EclipseState/EclipseState.cpp, lib/eclipse/EclipseState/Schedule/Schedule.cpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/EclipseState.hpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, lib/eclipse/tests/EclipseStateTests.cpp, lib/eclipse/tests/GeomodifierTests.cpp, lib/eclipse/tests/GroupTests.cpp, lib/eclipse/tests/MessageLimitTests.cpp, lib/eclipse/tests/ParseContextTests.cpp, lib/eclipse/tests/ScheduleTests.cpp, lib/eclipse/tests/SummaryConfigTests.cpp, lib/eclipse/tests/TuningTests.cpp, lib/eclipse/tests/WellSolventTests.cpp, lib/eclipse/tests/WellTests.cpp, lib/eclipse/tests/integration/CompletionsFromDeck.cpp, lib/eclipse/tests/integration/IOConfigIntegrationTest.cpp, lib/eclipse/tests/integration/ParseKEYWORD.cpp, lib/eclipse/tests/integration/ScheduleCreateFromDeck.cpp, lib/eclipse/tests/integration/TransMultIntegrationTests.cpp, lib/eclipse/tests/integration/parse_write.cpp
Depends on: 
https://github.com/OPM/opm-output/pull/207
https://github.com/OPM/opm-grid/pull/285
https://github.com/OPM/opm-core/pull/1182
https://github.com/OPM/ewoms/pull/233
https://github.com/OPM/opm-simulators/pull/1315
=> WIP: Extract schedule

lib/eclipse/Parser/Parser.cpp, lib/eclipse/Parser/ParserKeyword.cpp, lib/eclipse/include/opm/parser/eclipse/Parser/ParserKeyword.hpp, lib/eclipse/share/keywords/000_Eclipse100/A/AQUTAB, lib/eclipse/tests/ParserTests.cpp
This is special case code solely to satisfy the `AQUTAB` keyword.
=> Added optional shift attribute in keyword size configuration.

lib/eclipse/EclipseState/Schedule/Schedule.cpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
Added Schedule constructor which takes `EclipseState`argument.
=> New sched ctx

lib/eclipse/EclipseState/Schedule/Group.cpp, lib/eclipse/EclipseState/Schedule/Schedule.cpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/Schedule/Group.hpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp, lib/eclipse/tests/GroupTests.cpp
VFP table from GRUPNET keyword is added to Group in EclipseState for further use in Sunbeam
=> WIP: adding VFP table from GRUPNET

lib/eclipse/CMakeLists.txt, lib/eclipse/include/opm/parser/eclipse/EclipseState/Tables/Aqudims.hpp, lib/eclipse/tests/AqudimsTests.cpp
An aqudims class to hold on to the values from the AQUDIMS keyword + unit test. PR 1 of #1155
=> Introduce an aqudims class + test

debian/libopm-parser1-dev.install, redhat/opm-parser.spec
update the packaging files accordingly
=> fixed: cmake files are now installed to the appropriate arch directory

lib/eclipse/share/keywords/000_Eclipse100/F/FRICTION, lib/eclipse/share/keywords/keyword_list.cmake
Just to make some model can be parsed.
=> adding keyword FRICTION

lib/eclipse/EclipseState/Schedule/OilVaporizationProperties.cpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.hpp
quells a static analyzer warning
=> changed: pass by const ref

lib/eclipse/CMakeLists.txt
Ref https://github.com/OPM/opm-parser/blob/master/lib/eclipse/CMakeLists.txt#L180
=> changed: remove duplicated test

lib/eclipse/EclipseState/Eclipse3DProperties.cpp, lib/eclipse/EclipseState/Grid/GridProperties.cpp, lib/eclipse/EclipseState/Grid/GridProperty.cpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/Eclipse3DProperties.hpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/Grid/GridProperties.hpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/Grid/GridProperty.hpp, lib/eclipse/tests/data/integration_tests/BOX/BOXTEST1, lib/eclipse/tests/integration/BoxTest.cpp
Added functionality, and some simple testing.
=> Support for kw MAXVALUE/MINVALUE.

lib/eclipse/EclipseState/Grid/Box.cpp, lib/eclipse/tests/AquanconTests.cpp
Doing a warning sweep, did not find much here! The test has some Windows line-endings that I did not change, don't recall if we have a policy about that.
=> Silence sign comparison warnings.

lib/eclipse/Units/UnitSystem.cpp, lib/eclipse/include/opm/parser/eclipse/Units/UnitSystem.hpp, lib/eclipse/tests/UnitTests.cpp
also, the UnitTests test was buggy because it tested absolute temperature when it was supposed to test the temperature.
this should fix #1202.
=> respect the fact that non-SI temperature may be offset from zero

lib/eclipse/Units/UnitSystem.cpp, lib/eclipse/include/opm/parser/eclipse/Units/UnitSystem.hpp, lib/eclipse/tests/UnitTests.cpp
=> Revert "respect the fact that non-SI temperature may be offset from zero"

CMakeLists_files.cmake, lib/eclipse/EclipseState/AquiferCT.cpp, lib/eclipse/include/opm/parser/eclipse/EclipseState/AquiferCT.hpp, lib/eclipse/tests/AquiferCTTests.cpp
A C-T aquifer object to collect information from keywords AQUCT, AQUANCON and AQUTAB
=> Carter-Tracy aquifer object 
