- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
Change so that the status of a well do not change to open if there is no open completions.
Fredrik Gundersen
fgun@statoil.com
> Open well shut completions

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Tables/GasvisctTable.hpp
- opm/parser/eclipse/EclipseState/Tables/OilvisctTable.hpp
- opm/parser/eclipse/EclipseState/Tables/SingleRecordTable.cpp
- opm/parser/eclipse/EclipseState/Tables/SingleRecordTable.hpp
- opm/parser/eclipse/EclipseState/Tables/WatvisctTable.hpp
- opm/parser/share/keywords/000_Eclipse100/O/OILVISCT
- opm/parser/share/keywords/000_Eclipse100/W/WATVISCT
- opm/parser/share/keywords/001_Eclipse300/G/GASVISCT
- opm/parser/share/keywords/001_Eclipse300/O/OILVTIM
this is the second go at the temperature dependent viscosity stuff for the parser. IMO #405 was done a bit prematurely because the error it contained did not regress anything and it only affected the GASVISCT keyword which is E300 only and is not (cannot be?) used by the current versions opm-core and opm-autdiff... (at least it is not useful for them as long as those modules do not handle compositional flow.)
> Temperature dependent viscosity v2

- opm/parser/share/keywords/001_Eclipse300/C/COMPS
during #406, I noticed that the "COMPS" keyword was missing. this patch fixes that. Note that current code should not be affected at all because currently it only does E100 stuff and the parser will throw uppon encountering COMPS in a deck. (if I did not miss something recently, which may very well be.)
> Add the "COMPS" E300 keyword

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
quite a few important methods (e.g., getWells()) missed the variants
which are marked as 'const'. this leads to the problem that these methods
can't be called on the object returned by EclipseState::getSchedule()
because it returns a ScheduleConstPtr. (this issue can possibly also be
worked-around by creating a new mutable copy of the schedule object
from the one returned by EclipseState::getSchedule(), but to me, this
seems to be a strikingly inelegant and inefficient hack...)
this fixes the compilation of the ECL blackoil simulator of eWoms...
> allow the schedule object to be immutable

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
- opm/parser/share/keywords/000_Eclipse100/S/SAVE
Changed the implementation which prompted the removal of `const` in the first place, and removed some not needed non `const methods`
> Getwells const

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
- opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
- opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
- opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.hpp
- opm/parser/eclipse/EclipseState/SimulationConfig/tests/CMakeLists.txt
- opm/parser/eclipse/EclipseState/SimulationConfig/tests/SimulationConfigTest.cpp
- opm/parser/eclipse/EclipseState/SimulationConfig/tests/ThresholdPressureTest.cpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
Extended EclipseState with threshold pressure values:
Added new classes SimulationConfig and ThresholdPressure.
EclipseState has a new member, - an instance of the new SimulationConfig class. 
A get method for fetching this object is added to EclipseState.
From this SimulationConfig object a thresholdpressure vector can be fetched. 
The internalizing of the THPRES values are located in a separate class ThresholdPressure. 
SimulationConfig has got a member object of type ThresholdPressure.
Added tests for new class SimulationConfig and new class ThresholdPressure.
> OPM-166: Internalized tresholdPressure in EclipseState

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/share/keywords/000_Eclipse100/W/WCONINJE
it turns out that, in contrast to the RATE item, this item is always a
liquid rate (-> bbl/day in FIELD units), i.e., the dimension is always
"LiquidVolume/Time" irrespectibly of the fluid phase.
> Schedule: fix handling of the RESV item of the WCONINE keyword

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/Parser/ParserDoubleItem.cpp
- opm/parser/eclipse/Parser/ParserIntItem.cpp
- opm/parser/eclipse/Parser/ParserItem.cpp
The warnings are:
sizeType --> p_sizeType since it shadows a member method
trailing ;
comparison of signed and unsigned int
> Remove some warnings when compiling the parser module.

- opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
The function createMinpvDefaultCPDeck() was never used. I have just added the test that seemed to be forgotten.
> Add missing throw check, also silencing warning.

- opm/parser/eclipse/Applications/opm-eclkw.cpp
- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/Util/ElasticVector.hpp
- opm/parser/eclipse/EclipseState/Util/tests/CMakeLists.txt
- opm/parser/eclipse/EclipseState/Util/tests/ElasticVectorTests.cpp
- opm/parser/eclipse/IntegrationTests/IntegrationTests.cpp
- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/ParserKeyword.cpp
- opm/parser/eclipse/Parser/ParserKeyword.hpp
- opm/parser/eclipse/Parser/createDefaultKeywordList.cpp
- opm/parser/eclipse/Parser/tests/ParserKeywordTests.cpp
- opm/parser/eclipse/Parser/tests/ParserTests.cpp
Small first step towards supporting multi record keyword configuration; required for the VFP keywords.
1. Added small utility class ElasticVector<T> which will return the last valid  value when index >= size().
2. Stored ParserRecords in ElasticVector<>.
> Record vector

- opm/parser/eclipse/EclipseState/Tables/OilvisctTable.hpp
- opm/parser/eclipse/EclipseState/Tables/WatvisctTable.hpp
- opm/parser/eclipse/Units/ConversionFactors.hpp
- opm/parser/eclipse/Units/UnitSystem.cpp
- opm/parser/share/keywords/000_Eclipse100/V/VISCREF
- opm/parser/share/keywords/001_Eclipse300/C/COMPS
- opm/parser/share/keywords/001_Eclipse300/C/CREF
- opm/parser/share/keywords/001_Eclipse300/C/CREFS
- opm/parser/share/keywords/001_Eclipse300/D/DREF
- opm/parser/share/keywords/001_Eclipse300/D/DREFS
- opm/parser/share/keywords/001_Eclipse300/M/MW
- opm/parser/share/keywords/001_Eclipse300/M/MWS
- opm/parser/share/keywords/001_Eclipse300/O/OILCOMPR
- opm/parser/share/keywords/001_Eclipse300/O/OILMW
- opm/parser/share/keywords/001_Eclipse300/P/PREF
- opm/parser/share/keywords/001_Eclipse300/P/PREFS
- opm/parser/share/keywords/001_Eclipse300/S/STCOND
- opm/parser/share/keywords/001_Eclipse300/T/THERMAL
- opm/parser/share/keywords/001_Eclipse300/T/THERMEX1
- opm/parser/share/keywords/001_Eclipse300/T/TREF
- opm/parser/share/keywords/001_Eclipse300/T/TREFS
- opm/parser/share/keywords/001_Eclipse300/W/WATDENT
- opm/parser/share/keywords/001_Eclipse300/Z/ZFACT1
- opm/parser/share/keywords/001_Eclipse300/Z/ZFACT1S
- opm/parser/share/keywords/001_Eclipse300/Z/ZFACTOR
- opm/parser/share/keywords/001_Eclipse300/Z/ZFACTORS
- opm/parser/share/keywords/900_OPM/G/GCOMPIDX
- opm/parser/share/keywords/900_OPM/O/OCOMPIDX
this adds the stuff which is required to implement a "pseudo-thermal" black oil simulator. The main thing to be noted is that some Eclipse keywords use thermodynamic temperatures (Rankine or Kelvin) instead of "ordinary" ones (Fahrenheit or Celsius). This makes it necessary to introduce an "AbsoluteTemperature" unit...
> Implement temperature dependent density

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
- opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
- opm/parser/eclipse/EclipseState/Grid/tests/ADDREGTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/CopyRegTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/EqualRegTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/MULTREGTScannerTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/MultiRegTests.cpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
The GRIDOPTS keyword has some weird behaviour  - something like this: "If the second item is defaulted the default region for the xxxxREG keywords changes from MULTNUM to FLUXNUM". I think. 
If someone knows for sure that I have misunderstood this weird behaviour I would be very happy for a tip.
See the comment here for more details: https://github.com/joakim-hove/opm-parser/blob/default-region/opm/parser/eclipse/EclipseState/EclipseState.cpp#L417
With this PR applied it should not be necessary to perform the FLUXNUM -> MULTNUM copy.
> Default region

- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
Added method getGlobalIndex to EclipseGrid, needed from opm-core EclipseWriter
> OPM-157: Added method getGlobalIndex to EclipseGrid

- opm/parser/eclipse/Units/UnitSystem.cpp
- opm/parser/eclipse/Units/UnitSystem.hpp
OPM-157: Added enum UnitType in UnitSystem.  Using this enum when creating an UnitSystem instance.
> OPM-157: Added enum UnitType

- opm/parser/eclipse/Units/UnitSystem.cpp
- opm/parser/eclipse/Units/UnitSystem.hpp
This triggers compiler warnings at high warning levels.
> Remove surplus const for return-by-value.

- opm/parser/eclipse/OpmLog/Logger.cpp
- opm/parser/eclipse/OpmLog/tests/OpmLogTests.cpp
This suppresses two unused argument warnings. With this, all of opm-parser compiles with no warnings at a very high warning level.
> Fix warnings

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp
- opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
Handling keyword WELTARG. This keyword is used to modify WellProductionProperties for the spesified wells - at the specified timestep. 
Modified files:
WellProductionProperties.cpp,
WellProductionProperties.hpp,
Schedule.cpp,
Schedule.hpp,
ScheduleTests.cpp.
> OPM-87, added code for handling keyword WELTARG.

- opm/json/CMakeLists.txt
- opm/parser/eclipse/CMakeLists.txt
installed objects needs to be versioned. this is a quick fix for the release branch, should be fixed by using the shared build system in later releases.
> quick fix: set soversion for installed objects

- cmake/Modules/OpmProject.cmake
- debian/libopm-parser1-dev.install
multiarch had not been setup and the _TARGET variable is not set
in this build system.
please backport.
> fixed: pkgconfig file

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Tables/PlyshlogTable.hpp
Summary:
1.  Adding the member functions for PlyshlogTable in class EclipseState, which is forgotten when adding the support for keyword PLYSHLOG.
2. Making the member functions of PLyshlogTable public and adding const to two functions to solving compiling error in opm-polymer.
> Adding member function for plyshlog to the class EclipseState

- opm/parser/eclipse/Applications/Schedule.cpp
- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
- opm/parser/eclipse/EclipseState/IOConfig/tests/CMakeLists.txt
- opm/parser/eclipse/EclipseState/IOConfig/tests/IOConfigTest.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
- opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/TimeMapTest.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/TuningTests.cpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
- opm/parser/eclipse/IntegrationTests/ParseWellWithWildcards.cpp
- opm/parser/eclipse/IntegrationTests/ScheduleCreateFromDeck.cpp
- opm/parser/share/keywords/000_Eclipse100/N/NOGGF
Added IOConfig class. The class holds data about input and output configuration; currently the following is supported:
- If UNIFIN/UNIFOUT/FMTIN/FMTOUT is set
- Should restart file be written at a given timestep (RPTRST keyword is supported)
- Should EGRID file be written (GRIDFILE / NOGGF keyword)
- Should INIT file be written (INIT keyword)
A const pointer to the IOConfig object can be fetched from EclipseState
> Opm 199 IOConfig

- opm/parser/eclipse/Applications/CMakeLists.txt
Sorry, forgot to test the all target, was only focused on tests.
> fix linking of applications after targets was renamed

- CMakeLists.txt
This locates opm-cmake using config-mode find_package by default. Needs https://github.com/OPM/opm-cmake/pull/9
> use config-mode for opm-cmake by default

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
- opm/parser/eclipse/EclipseState/IOConfig/tests/IOConfigTest.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
Also made constructor explicit since it now only takes a single argument, to avoid unintended implicit conversion.
All tests still succeed, and I do not thing there are downstream consequences (at least there were none in opm-core).
> Remove unused deck argument from IOConfig constructor.

- CMakeLists.txt
we do not look for generated headers in the source tree. @joakim-hove for review.
> fixed: copy dummy header in place

- CMakeLists.txt
needs to be duplicated here since opm-parser does not use OpmLibMain.cmake
> added: check-commits target

- opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/DynamicStateTests.cpp
This small PR adds the ability to reset the content of DynamicState<T> property - this is support full global override of properties which can be specified both in the deck and on the commandline.
> Added method globalReset() to DynamicState<T>

- CMakeLists.txt
so far, the `CMAKE_CXX_FLAGS` variable was always set to the value specified in `CMakeLists.txt`. This leads to undefined symbols if the libstdc++ debug mode is used by downstream modules. (i.e., if the
`_GLIBCXX_DEBUG` macro is defined.)
> do not override custom C and C++ compiler flags

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
- opm/parser/eclipse/EclipseState/IOConfig/tests/IOConfigTest.cpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
Opm 212: Extend IOConfig to support override of RESTART config from deck with config from param
> Opm 212: Extend IOConfig to support override of RESTART config 

- opm/parser/eclipse/EclipseState/IOConfig/tests/IOConfigTest.cpp
The `timestep` variable name was already used.
> Silence shadowing warning.

- opm/parser/eclipse/Deck/Deck.cpp
- opm/parser/eclipse/Deck/Deck.hpp
- opm/parser/eclipse/Deck/tests/DeckTests.cpp
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/Grid/FaultCollection.cpp
- opm/parser/eclipse/EclipseState/Grid/FaultCollection.hpp
- opm/parser/eclipse/EclipseState/Grid/NNC.cpp
- opm/parser/eclipse/IntegrationTests/CMakeLists.txt
- opm/parser/eclipse/IntegrationTests/ResinsightTest.cpp
- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/Parser.hpp
- testdata/integration_tests/Resinsight/DECK1.DATA
Have introduced a flag bool flag for relaxed parsing. The main purpose of this is that one can create a custom parser with only some keywords, this parser will then ignore the unknown keywords gracefully.
The flag is defaulted to `false` - i.e. no change in behavior, see: bceb824 for more details and an example.
> Relaxed parse

- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
Fixed IOConfig compiler warning;  wrong return type for method overrideRestartWriteInterval. Should be void, not bool.
> Fixed IOConfig compiler warning;  wrong return type for method overrideRestartWriteInterval

- opm/parser/eclipse/Generator/KeywordGenerator.cpp
- opm/parser/eclipse/Generator/KeywordGenerator.hpp
This fixes one of the problems described in #501.
A few notes:
- Now that we can assume quite new compiler versions we can finally use the std::string constructor of the file stream classes!
- I used scoping to ensure the input stream is closed before the output stream opens. For all I know it was perfectly legal the way it was used, but it certainly opens the door to extremely thorny issues of how they would interact so it is better to keep them apart.
- I could not see any tests for this, if there are any, where should I check?
> Improve updateFile and suppress warnings.

- opm/parser/eclipse/CMakeLists.txt
This change-set marks the `VFP*Table.hpp` header files as installable.  That, in turn, is needed for consumers of an installed opm-parser module.
> Install VFP Table Headers

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp
- opm/parser/eclipse/EclipseState/Grid/tests/GridPropertyTests.cpp
i.e., the PC[GW] and KR[OGW] properties plus their imbibition and
directional variants. the properties required for three-point vertical
scaling (i.e., KRWR, et al.) are still to be done.
currently, vertical endpoint scaling is not supported by the satuation functions of opm-core, but it is wise for the parser to not stand in the way.
> add grid properties required for the simple "vertical" endpoint scaling

- opm/parser/eclipse/EclipseState/EclipseState.cpp
This method was not used anywhere yet, so the error was not discovered.
> Add missing method implementation for hasNNC().

- opm/parser/eclipse/EclipseState/EclipseState.cpp
The long list caused extreme compile-times for clang in optimised mode. This cuts compilation time for EclipseState.cpp down to 11 seconds, down from almost 3 minutes. The recent addition of many more elements to the list made compile time explode. Probably one or more of the optimisation passes uses a bad (n^2) algorithm or uses so much memory that my 8 GB system started swapping.
In any case, this fixes my problem, and I'd say that the code is a little bit less mysterious when lines are terminated by semicolons not colons...
It is hard to review the changes here in the diff unfortunately, so this is a description:
1) Create an empty supportedDoubleKeywords instead of an initialised one.
2) Add all members with
```
supportedDoubleKeywords->emplace_back( "SGL"    , SGLLookup, "1" );
``` …
> Avoid using extremely long initialiser list.

- opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp
- opm/parser/eclipse/EclipseState/Grid/tests/GridPropertyTests.cpp
At least I hope it's correct: the condition for breaking the loops
where inverted in some places.
thanks to [at]bska for discovering this.
this PR should fix #520, but it would be good if @bska could confirm this
> SatfuncPropertyInitializer: determine the critical saturations correctly

- opm/parser/eclipse/Parser/tests/ParserIncludeTests.cpp
This is necessary to compile on Mac OS X.
> Update case-insensitive-filesystem tests to use new ParserMode.

- opm/parser/eclipse/EclipseState/Tables/VFPProdTable.cpp
This should somewhat address what @andlaus reported about the verbosity level of VFP tables.
> Updated printout to be less verbose for not-so-nice data

- CMakeLists.txt
- opm/core/CMakeLists.txt
- opm/core/utility/platform_dependent/disable_warnings.h
- opm/core/utility/platform_dependent/reenable_warnings.h
This should be merged simultaneously with the corresponding PR in opm-core that removes the header from there. Please review the (small) CMake changes, as I am not intimately familiar with how things should be done in opm-parser (since it does not use the exact same approach to adding files as the other modules do). The actual headers are the same as before.
This is a pragmatic move to make it possible to use this functionality in opm-parser. In the longer term the headers should end up in the topmost core module of opm (which no longer opm-core can be said to be). Keeping the paths identical means that no client code needs to change.
> Add warning-suppression utility headers.

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
- opm/parser/eclipse/EclipseState/SimulationConfig/tests/ThresholdPressureTest.cpp
- opm/parser/eclipse/IntegrationTests/ParseEQUIL.cpp
- opm/parser/eclipse/IntegrationTests/ResinsightTest.cpp
- opm/parser/eclipse/Parser/ParseMode.cpp
- opm/parser/eclipse/Parser/ParseMode.hpp
- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/tests/ParseModeTests.cpp
With this PR the implementation of the ParseMode class has changed completely. Instead of hardwiring  the error scenarios the implementation is based on a map strings and expected action. The main advantage of this is that it becomes easier and more flexible to add update the policy.
When updating a policy you send a string which can contain '?' and '*' and several settings split by '|'. So to ignore all errors arising from unsupported features and random '/' found in the input:
````
parserMode.update("UNSUPPORTED_*|PARSER_RANDOM_SLASH" , InputError::IGNORE)
```
By default the ParseMode object will be instantiated with all settings set to `InputError::THROW_EXCEPTION` - but before returning the constructor will consult the environment variables `OPM_ERRORS_IGNORE, OPM_ERRORS_WARN` and …
> Reimplmented ParseMode based on string keys.

- opm/parser/eclipse/EclipseState/Schedule/Group.cpp
- opm/parser/eclipse/EclipseState/Schedule/Group.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/share/keywords/000_Eclipse100/G/GCONPROD
Also change defaults for production rate properties to -999e100, since 0 is an actual possible rate, and while it would be possible to ask if a default was applied (the default should be no rate or limit, not a zero rate), unlike for wells there are no methods doing this currently.
> Add reservoirVolumeTarget property for group production.

- opm/parser/eclipse/EclipseState/Grid/tests/GridPropertyTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/SatfuncPropertyInitializersTests.cpp
OIL, GAS and WATER is specified to avoid the 3-phase assert test in
SatfuncPropertyInitializers to fail. 
See #556
> Add phase info to tests

- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/Parser.hpp
- opm/parser/eclipse/Parser/tests/ParserTests.cpp
With this we should handle case like this: https://github.com/OPM/opm-parser/issues/561
> Handle quotes when stripping off comments.

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp
- opm/parser/eclipse/EclipseState/Tables/SlgofTable.hpp
- opm/parser/eclipse/IntegrationTests/CMakeLists.txt
- opm/parser/eclipse/IntegrationTests/ParseSLGOF.cpp
as far as I can see, SLGOF is the same as SGOF but with the saturation column defined as So + Swco (instead of Sg), so everything is reversed. (wow! what a wonderful concept!) Also this is probably the last table (except for, maybe, for SOF2 and friends) which is required to support the family 1 saturation functions fully.
> Support slgof

- opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
I just suppressed the warning, did not check if the argument actually *should* be used.
> Silence unused argument warning.

- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp
Unfortunately checked in error in (not yet used) enum conversion method. Now fixed.
> OPM-222: Fixed error in completionorder enum conversion method

- CMakeLists.txt
- opm/parser/eclipse/CMakeLists.txt
The 'deploy flow' workflow I currently use is as follows:
```python
for module in [opm-common, opm-parser, opm-material, ....] 
git fetch & checkout
cmake -DCMAKE_INSTALL_PREFIX=/path/to/install -DCMAKE_PREFIX_PATH=/path/to/install ...
make install
```
I.e. the modules are built and installed in order, where each downstream module typically finds it's dependencies in the already installed location. This works reasonably well - but I just had problems compiling the parser - because instead of using the in-source version of an include file, it found an old version in the installation directory. So to solve(?) this I have added `BEFORE` when configuring the include directories for the parser:
1. Is this frowned upon?
2. If it is indeed a valid way to do it - I guess the same could be applied …
> Added BEFORE attribute to include_directories( )

- opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
- opm/parser/eclipse/EclipseState/SimulationConfig/tests/SimulationConfigTest.cpp
- opm/parser/share/keywords/000_Eclipse100/C/CPR
The following has happened:
1. In https://github.com/OPM/opm-parser/pull/581 we added support for internalizing the CPR keyword.
2. In https://github.com/OPM/opm-autodiff/issues/489 @dr-robertk reported that flow/parser could no langer handle an old version of the SPE9 data.
It turns out that the old SPE9 input deck has a `CPR` keyword in the summary section: https://github.com/OPM/opm-data/blob/9af155c26bc0946d9af846ac6e503115c0267050/spe9/SPE9.DATA - this keyword has completely different schema than the keyword added in #581, and the parsing goes completely belly up. The current 'fix' is just to revert the functionality of #581 - but the longer term fix must determine one two:
1. I have found no references to `CPR` in the `SUMMARY` section in the documentation, maybe it is a "bug" in …
> Temporarily remove parser support for CPR keyword

- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
- opm/parser/eclipse/EclipseState/IOConfig/tests/IOConfigTest.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
- opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/TimeMapTest.cpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
- opm/parser/eclipse/IntegrationTests/IOConfigIntegrationTest.cpp
- testdata/integration_tests/IOConfig/SPE1CASE2.DATA
Testing have revealed difference in behaviour for when restart files are written for Eclipse and Flow
for RPTRST basic = 3/4/5 settings. 
This have now been fixed, and more testing that compares IOConfig settings with results as written from eclipse for the same settings (Integration tests) have been added.
> Opm 218 fix

- opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
Eliminates a compile warning, and makes the code clearer.
> Avoid shadowing the 'record' variable.

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
This PR adds support for item 10 in welspecs where a flag is used to
determine whether the well should allow cross flow or not.
A test is added to check default behavior.
> Add flag allowCrossFlow()

- opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.cpp
- opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.hpp
What matters is the type (const or not) used at the call site. It does not matter if the method returns a const. Note that this applies to value types, not references.
Update: the reason I fix this is that it generates a warning for me.
> Do not use const for value return.

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
Note: Producing wells in prediction mode is kept open even if the
control rate is set to zero.
> Shut wells with zero rates and crossflow not allowed

- CMakeLists.txt
- opm/json/CMakeLists.txt
- opm/parser/eclipse/CMakeLists.txt
This was quick-fixed for last release. Now uses the information from the dune.module file to set versions.
> added/fixed: set soversion for libraries

- opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp
In particular this warning is removed:
```
In file included from /home/mblatt/src/dune/opm/opm-parser/opm/parser/eclipse/EclipseState/EclipseState.cpp:34:0:
/home/mblatt/src/dune/opm/opm-parser/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp:438:66: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
const SaturationFunctionFamily getSaturationFunctionFamily() const{
^
```
Probably this should go to the release, too.
> Fixes warning about ignored qualifiers on function return types.

- opm/parser/eclipse/Deck/tests/DeckTests.cpp
it seems that recent Boost versions (I used 1.59) enforce a semicolon
behind the BOOST_CHECK macros, while older ones did not.
> fix build when using newish Boost libraries

- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp
- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.hpp
It is hard to judge from the manual, but H0 and not HO is used in the new model.
> Rename from HO to H0

- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp
- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.hpp
To fix a failed test.
Internally and output we still use `HO`.
> handling both HO and H0 for mutliphase model input

- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
This makes it easier to write code using this function (see OPM/opm-autodiff#543).
The tests needed no changes since they used `auto` for the return type and an std::array supports the std::tuple interface.
> Change return type from tuple to array for getCellCenter().

- opm/parser/eclipse/EclipseState/Schedule/DynamicVector.hpp
> Use warning suppression headers to avoid warnings from boost.

- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
Added a new method getRestartFileName(const std::string& restart_base, int report_step) to IOConfig. 
The parameters are the restart_base and report_step given in the RESTART keyword in the DATA file, located in the initConfig object. 
I will be using this method from the restart functionality code in autodiff. (not yet a PR for this).
There are some things I wonder about here though , - what about support for higher restart numbers than 9999? As you can see from the code this is not supported here, and I can't see that Eclipse supports it either, but I am sure that I am wrong. So please enlighten me on this subject. 
Or maybe the ert code has functionality for getting the name of a restart file?
> OPM-250: Minor changes to support restart

- opm/parser/eclipse/IntegrationTests/ParseMiscible.cpp
I still do not really know why this is not always triggered, probably not all tests instantiate every template. Content to fix as they turn up though...
> Add warning suppression includes.

- opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
- opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
- opm/parser/eclipse/EclipseState/SimulationConfig/tests/SimulationConfigTest.cpp
Added VAPOIL, DISGAS to SimulationConfig. To be used from EclipseReader (opm-core) for restart functionality
> OPM-252: Added VAPOIL, DISGAS to SimulationConfig

- opm/parser/eclipse/CMakeLists.txt
Pretty self-explanatory. The makefile has a bug which installs autogenerated headers into the wrong directory.
> Fixes autogen'd .hpp installed into wrong dir

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
Similar to the already-existant Schedule::getWells, this simple method
returns (const) pointers to all groups, suitable for iteration, maps and
for-all-in operations.
> Adds Schedule::getGroups()

- opm/parser/eclipse/Deck/DeckItem.cpp
- opm/parser/eclipse/Deck/DeckItem.hpp
- opm/parser/eclipse/Deck/tests/DeckDoubleItemTests.cpp
- opm/parser/eclipse/Deck/tests/DeckIntItemTests.cpp
- opm/parser/eclipse/Deck/tests/DeckStringItemTests.cpp
This feature is not used at all. I suggest it is removed, and if a need arises it can be reintroduced.
> Removes push_back( deque ) from DeckItem

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/share/keywords/000_Eclipse100/M/MISCNUM
- MISCNUM is used to specify miscibility regions
> Add support for MISCNUM

- opm/parser/share/keywords/000_Eclipse100/P/PVCDO
Fixing the unit of the oil compressibility. Make one of my simulation with PVCDO keyword much better.
Should affect OPM/opm-autodiff#568, while not sure how yet.
> fixing the unit of the compressibility in PVCDO keyword.

- opm/parser/eclipse/Applications/opm-eclkw.cpp
- opm/parser/eclipse/IntegrationTests/IntegrationTests.cpp
- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/Parser.hpp
- opm/parser/eclipse/Parser/tests/ParserIncludeTests.cpp
- opm/parser/eclipse/Parser/tests/ParserTests.cpp
Removes shared_ptr< ParserKeyword > exchange in Parser interface and
replaces it with unique_ptr storage and raw pointers for return values.
This has some implications:
* addParserKeyword() no longer takes shared_ptr<>, but unique_ptr&&
addParserKeyword has been modified to create unique_ptr instead of
shared_ptr.
* generated-source/ParserKeyword* no longer use make_shared which had a
-massive- impact on compile times, which are now more-or-less
trivialised (on my machine: 7.5s -> 1s per file). This because the
compiler no longer generates a bunch of forwarding make_shared
instances of subclasses that are immediately thrown away, but rather
uses an inline make_unique that instantiates the -parent- class
unique_ptr.
> Parser stores keywords as unique_ptr

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/Summary/Summary.cpp
- opm/parser/eclipse/EclipseState/Summary/Summary.hpp
- opm/parser/eclipse/EclipseState/Summary/tests/CMakeLists.txt
- opm/parser/eclipse/EclipseState/Summary/tests/SummaryTests.cpp
This will be rebased on master once https://github.com/OPM/opm-parser/pull/677 is merged as it depends on it.
This patch internalises a representation of the SUMMARY section of an input deck, data that can later be passed to some writers that determines what to output.
Uses ERT::smspec_node for the internal representation.
> Internalise SUMMARY section

- opm/parser/eclipse/Utility/Functional.hpp
- opm/parser/eclipse/Utility/tests/FunctionalTests.cpp
Fix a missing include (accumulate is in the algorithm header) and silence boost warnings.
Another thing I noticed is that the new files do not carry the copyright/license block at the top as it should. It is good to add hooks to your editor to always add this, if possible.
> Minor fixes

- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
With this, the ACTNUM keyword can be used to deactivate cells also when the cartesian grid keywords (DX/DY/DZ/TOPS or DXV/DYV/DZV/DEPTHZ) are used to specify the grid.
Thanks to Mark Khait for providing model exhibiting the problem.
> Honor the ACTNUM keyword also for cartesian grids.

- opm/parser/eclipse/Parser/ParserDoubleItem.cpp
- opm/parser/eclipse/RawDeck/StarToken.cpp
- opm/parser/eclipse/RawDeck/StarToken.hpp
- opm/parser/eclipse/RawDeck/tests/StarTokenTests.cpp
The templated readValueToken has been moved to source file, and uses
explicit instantiation and linking. The deprecated float specialisation
has been removed.
> Moves readValueToken implementation to source file

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
- opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
- opm/parser/eclipse/EclipseState/Tables/Tables.cpp
- opm/parser/eclipse/EclipseState/Tables/TlpmixpaTable.hpp
- opm/parser/eclipse/IntegrationTests/ParseMiscible.cpp
- opm/parser/share/keywords/900_OPM/T/TLPMIXPA
The TLPMIXPA keyword can be used for giving pressure depended Todd-
Longstaff parameters. The implementation follows the description of
PMISC.
> Add new keyword TLPMIXPA

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/Deck/DeckItem.cpp
- opm/parser/eclipse/Deck/DeckItem.hpp
- opm/parser/eclipse/Deck/DeckRecord.cpp
- opm/parser/eclipse/Deck/DeckRecord.hpp
- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/Parser.hpp
- opm/parser/eclipse/Parser/ParserItem.hpp
- opm/parser/eclipse/Parser/ParserKeyword.cpp
- opm/parser/eclipse/Parser/ParserRecord.cpp
- opm/parser/eclipse/RawDeck/RawConsts.hpp
- opm/parser/eclipse/RawDeck/RawKeyword.cpp
- opm/parser/eclipse/RawDeck/RawKeyword.hpp
- opm/parser/eclipse/RawDeck/RawRecord.cpp
- opm/parser/eclipse/RawDeck/RawRecord.hpp
- opm/parser/eclipse/RawDeck/StarToken.cpp
- opm/parser/eclipse/RawDeck/StarToken.hpp
- opm/parser/eclipse/RawDeck/tests/RawKeywordTests.cpp
- opm/parser/eclipse/RawDeck/tests/RawRecordTests.cpp
- opm/parser/eclipse/RawDeck/tests/StarTokenTests.cpp
- opm/parser/eclipse/Utility/Stringview.cpp
- opm/parser/eclipse/Utility/Stringview.hpp
- opm/parser/eclipse/Utility/tests/CMakeLists.txt
- opm/parser/eclipse/Utility/tests/StringviewTests.cpp
Depends on https://github.com/OPM/opm-parser/pull/705
This patch set addresses some of the performance shortcomings and inefficiencies in opm-parsers, mostly tracked down using valgrind (callgrind). Each individual commit addresses some specific aspect. A short summary:
* string_view is a std::string interface compatible (not completely, but on a by-need basis) view into a (sub)string to avoid copying too many strings.
* boost algorithms have been replaced by faster hand-rolled (locale-ignoring) versions.
* some containers take size hints and preallocates memory.
* some algorithmic improvements and heuristics applied.
> Parser performance improvements

- opm/parser/eclipse/Deck/Deck.cpp
- opm/parser/eclipse/Deck/Deck.hpp
- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/Parser.hpp
- opm/parser/eclipse/Parser/tests/ParserTests.cpp
- opm/parser/eclipse/RawDeck/StarToken.cpp
- opm/parser/eclipse/Utility/Stringview.hpp
Fixes a set of flaws and vulnerabilities.
Summary:
* Default constructed Decks now have valid (albeit trivial) iterators, meaning they no longer invoker undefined behaviour under testing. (Thanks for the report!)
* Removes a buggy and unused method
* Fixes a potential buffer overflow vulnerability by checking input sizes. integer buffer size is determined from platform int size, whereas double uses a heuristic.
Testing very much welcome.
> Initialisation and memory errors fixed

- .travis.yml
- travis/build-opm-parser.sh
1. The build-opm-parser.sh script - which is used by downstream
modules, does not build the Python bindings.
2. The main travis script uses the build-shared script from opm-common.
> Changes in travis configuration

- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleEnumTests.cpp
Should fix: https://github.com/OPM/opm-parser/issues/722
> Allow 'WAT' when parsing type string in WCONINJE.

- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/RawDeck/RawKeyword.cpp
- opm/parser/eclipse/RawDeck/RawKeyword.hpp
Removes some undefined behaviour introduced by iterator invalidation (string_view's) caused by reallocation of the `m_records` vector.
The quick solution has been to replace `std::vector` with `std::list`. Performance-wise this takes us back to square one, but we're no worse off than we were storing a vector of `std::shared_ptr`.
Additionally, iterators have been introduced on `RawKeyword`, since expected use of `RawKeyword` is to facilitate iteration over `RawRecords`.
> RawKeyword iterator support and correct RawRecord management

- opm/parser/eclipse/RawDeck/StarToken.cpp
- opm/parser/eclipse/RawDeck/tests/StarTokenTests.cpp
Changes the implementation of numbers parsing from std::atoi/f to
std::strtod/l. These support setting the optional end-of-string pointer
which are used to determine if a parsing was successful or not. This has
the nice side effect of *greatly* simplifying the logic, at the expense
of some C-style details.
Tests added to verify that the different edge cases are handled
properly.
Fixes issue https://github.com/OPM/opm-parser/issues/740
> ReadValueToken correctly parses numbers

- jenkins/README.md
- jenkins/build-opm-parser.sh
- jenkins/build-pr.sh
- jenkins/build.sh
This is the Jenkins build scripts for this module, ref https://github.com/OPM/opm-common/pull/102
These files here serve the following purposes:
- README.md - simple instruction on how to use/setup on Jenkins.
- build.sh - Script intended for post-merge builds on Jenkins.
- build-pr.sh - Script intended for pre-merge pull request builds on Jenkins (through a trigger).
- build-opm-parser.sh - Shared code between the two build modes.
I have included ERT for my own convenience, although there is no trigger support to build against a PR there. Whether this is wanted or not I leave up to others to decide (trigger support is easily added if you want to take it all the way).
Basically, the pre-merge builds works through a trigger. Authorized persons can comment on a pull request to have Jenkins …
> Jenkins reboot

- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/ParserKeyword.cpp
- opm/parser/eclipse/RawDeck/RawKeyword.cpp
- opm/parser/eclipse/RawDeck/RawKeyword.hpp
- opm/parser/eclipse/RawDeck/tests/RawKeywordTests.cpp
Using range based for instead of `getRecord( )`when iterating over `RawRecords`.
The `std::next( )` based solution chocked when meeting a keyword with O(400000) records.
> Rawkeyword iterator

- opm/parser/eclipse/Parser/MessageContainer.cpp
- opm/parser/eclipse/Parser/MessageContainer.hpp
- opm/parser/eclipse/Parser/ParseContext.cpp
- opm/parser/eclipse/Parser/ParseContext.hpp
- opm/parser/eclipse/Parser/tests/MessageContainerTest.cpp
As a step towards (re)making `ParseContext` a read-only configuration object, remove `MessageContainer` from parse context. The patch set also changes Messages to auto-only storage, deprecating `unique_ptr`s.
> Remove MessageContainer from ParseContext + storage type change

- .travis.yml
Travis will now build OPM/Parser on OSX with clang in addition to Linux with GCC
> Added clang support to Travis CI

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
Enable support for querying what fluid-in-point regions are defined in
the deck. For now the only interesting regions are the ones specified by
the FIPNUM keyword in the REGIONS section.
The implementation is somewhat inefficient (n log n over the number of
cells in the grid), but since this is likely to only be called when
default-expanding SUMMARY section keywords this isn't too bad, since the
implementation is so dead simple. 
--
This still need some good test cases before I'm comfortable merging it. I'm also not sure if this belongs directly onto the EclipseState or if it is a grid property. Opinions very welcome.
> Query the name of (FIP) regions in State

- opm/parser/eclipse/EclipseState/Grid/FaceDir.hpp
- opm/parser/eclipse/EclipseState/Grid/MinpvMode.hpp
- opm/parser/eclipse/EclipseState/Grid/PinchMode.hpp
- opm/parser/eclipse/EclipseState/Tables/ColumnSchema.hpp
- opm/parser/eclipse/EclipseState/Tables/TableColumn.hpp
- opm/parser/eclipse/EclipseState/Tables/TableEnums.hpp
- opm/parser/eclipse/EclipseState/Tables/TableIndex.hpp
- opm/parser/eclipse/EclipseState/Tables/TableSchema.hpp
- opm/parser/eclipse/EclipseState/Util/OrderedMap.hpp
- opm/parser/eclipse/EclipseState/Util/RecordVector.hpp
- opm/parser/eclipse/EclipseState/Util/Value.hpp
just like for macros that start and end with `__`, `clang++ -Weverything` likes to complain about macros which start and end with a single underscore. This is basically the same issue as Ensembles/ert#1048
> avoid reserved names for guard macros

- opm/parser/eclipse/Parser/Parser.hpp
this breaks with g++ 4.8 used in redhat builds.
/usr/include/boost148/boost/filesystem/v3/path.hpp:710:24 error: 'path'
is already declared in this scope.
Seems g++-4.8 has a bug; you cannot prototype symbols which are included from a different namespace. Boost (atleast 1.48) imports either boost::filesystem2::path or boost::filesystem3::path with a 'using' statement. This took me forever to track. This is the best I can do. The cost is small imo.
> changed: do not prototype boost::filesystem::path

- opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
- opm/parser/eclipse/EclipseState/Grid/GridProperty.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
- opm/parser/eclipse/EclipseState/SimulationConfig/tests/SimulationConfigTest.cpp
- opm/parser/eclipse/EclipseState/SimulationConfig/tests/ThresholdPressureTest.cpp
- opm/parser/eclipse/IntegrationTests/EclipseGridCreateFromDeck.cpp
* Added ACTNUM as keyword to Eclipse3DProperties
* Removed certain checks from EclipseGrid that are no longer of use
* Added tests to EclipseGridTests that test boxed ACTNUM and activeCells
* Made EclipseGrid non-const in EclipseState since we must run resetACTNUM
* Fixed a minor typo in an error message in EclipseGrid
* Fixed typo in GridProperty: Deckeyword -> DeckKeyword
* Fixed two errors in tests recently introduced relating to Ecl3DProps
* Removed test in EclipseGridTests; We now accept too small ACTNUM vectors
* Added ACTNUM test for GridProperties
> Fixes support for BOXed ACTNUM

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
- opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
- opm/parser/eclipse/EclipseState/Summary/Summary.cpp
- opm/parser/eclipse/EclipseState/tests/Eclipse3DPropertiesTests.cpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
- opm/parser/eclipse/IntegrationTests/BoxTest.cpp
- opm/parser/eclipse/IntegrationTests/EclipseGridCreateFromDeck.cpp
- opm/parser/eclipse/IntegrationTests/NNCTests.cpp
- opm/parser/eclipse/IntegrationTests/ParseTOPS.cpp
This commit introduces two changes:
* EclipseState.getEclipseGrid has been changed to getInputGrid
* EclipseGrid---ignoring ACTNUM in Deck as it now does---has a new constructor, one that explicitly (but default `nullptr`) takes an `const int* actnum`.
Relevant PR's from other repos:
* OPM/opm-output#18
* OPM/opm-material#141
* OPM/opm-core#1002
* OPM/opm-simulators#657
* OPM/ewoms#55
> Renamed getEclipseGrid to getInputGrid and changed EclipseGrid constructor

- opm/parser/eclipse/EclipseState/Grid/tests/SatfuncPropertyInitializersTests.cpp
- opm/parser/eclipse/EclipseState/SimulationConfig/tests/ThresholdPressureTest.cpp
- opm/parser/eclipse/EclipseState/tests/Eclipse3DPropertiesTests.cpp
Problem found by compiler warning. It is an extremely useful tool, and I highly recommend compiling at high warning levels (and activating the third-party header warning suppression).
Also fixed two shadowing warnings (think the code is a little more clear for it, too).
> Bugfix for a property test

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- opm/parser/eclipse/EclipseState/SummaryConfig/tests/CMakeLists.txt
- opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
This object turns out to be the actual configuration object, not a
mediator state to obtain a configuration. It is therefore renamed to
reflect intent and behaviour.
> Rename Summary to SummaryConfig

- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Utility/Stringview.hpp
Pretty much self-explanatory. A few downstream tests indicated a few possible sources of error.
> Remove possible sources of undefined behaviour

- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
- opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
This PR introduces one new method on `EclipseGrid`: essentially reimplementing (instead of exposing) `ecl_grid.h` function
```C
void ecl_grid_get_ijk1(const ecl_grid_type * , int global_index , int *, int * , int *);
```
> Added method getIJK in EclipseGrid

- CMakeLists.txt
- opm/parser/eclipse/Deck/Deck.hpp
This commit is a first step towards reducing the use of the Deck api
outside of opm-parser. Downstream modules should preferably use the
EclipseState api which is richer in features, and also easier to use
correctly.
The current form of the code is temporary, in the future we will remove
the OPM_PARSER_DECK_API_WARNING compile guard.
> Emit compiler warning when including Deck.hpp

- opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- opm/parser/eclipse/EclipseState/InitConfig/InitConfig.cpp
- opm/parser/eclipse/EclipseState/InitConfig/InitConfig.hpp
- opm/parser/eclipse/EclipseState/InitConfig/tests/InitConfigTest.cpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
Minor update to support: https://github.com/OPM/opm-parser/issues/773
PR in opm-simulators coming.
The SWAT / SGAS / PRESSURE keywords are added to the Eclipse3DProperites to enable enumerated restarts.
> Ignore skiprest

- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
Needed when reading deck from string and trying to write to disk.
If this is not set there is no baseName to base the file name on.
A _very_ special case. Will only ever be used by tests? Should we actually support this?
> Support explicit setting of BaseName

- opm/parser/eclipse/Deck/Deck.cpp
- opm/parser/eclipse/Deck/Deck.hpp
- opm/parser/eclipse/Deck/DeckItem.cpp
- opm/parser/eclipse/Deck/tests/DeckRecordTests.cpp
- opm/parser/eclipse/EclipseState/Grid/GridProperty.cpp
- opm/parser/eclipse/IntegrationTests/IntegrationTests.cpp
- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/Parser.hpp
- opm/parser/eclipse/Parser/ParserKeyword.cpp
- opm/parser/eclipse/Parser/ParserKeyword.hpp
- opm/parser/eclipse/Parser/tests/ParserItemTests.cpp
- opm/parser/eclipse/Parser/tests/ParserRecordTests.cpp
- opm/parser/eclipse/RawDeck/RawConsts.hpp
- opm/parser/eclipse/RawDeck/RawKeyword.cpp
- opm/parser/eclipse/RawDeck/RawKeyword.hpp
- opm/parser/eclipse/RawDeck/RawRecord.cpp
- opm/parser/eclipse/RawDeck/RawRecord.hpp
- opm/parser/eclipse/RawDeck/StarToken.cpp
- opm/parser/eclipse/RawDeck/StarToken.hpp
- opm/parser/eclipse/RawDeck/tests/RawRecordTests.cpp
- opm/parser/eclipse/Utility/Stringview.hpp
- opm/parser/eclipse/Utility/tests/StringviewTests.cpp
A somewhat large patch set of smaller incremental updates (for ease of review) designed to simplify the structure of the internal parsing, remove some redundant code and enable new optimisations. I've tried to keep every commit tiny and single-purpose. A few highlights:
* `string_view` uses char* internally instead of `std::string::const_iterator`
* streams removed in favour of reading the whole file at once and work with it in memory
* `RawRecord`s no longer copy memory, but stores offsets into the buffered file
* Simplified control flow of several helper functions
* The input file is immediately stripped for comments and other things to ignore - this reduces special casing and simplifies actual parsing
* Various performance benefits (I measure ~15%)
Except for speedups, no side effects …
> Refactoring of internal parsing

- jenkins/build-opm-parser.sh
- jenkins/build-pr.sh
use 'jenkins build this with downstreams please'.
this will build all downstreams against the PR, and
execute their tests. PR's for upstream and downstream modules
can be specified.
the aggregated test results are attached to the job result on jenkins.
depends on https://github.com/OPM/opm-common/pull/111
> added: downstream build support in the jenkins trigger

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
- opm/parser/eclipse/EclipseState/Grid/FaultCollection.cpp
- opm/parser/eclipse/EclipseState/Grid/FaultCollection.hpp
- opm/parser/eclipse/EclipseState/Grid/NNC.cpp
- opm/parser/eclipse/EclipseState/Grid/NNC.hpp
- opm/parser/eclipse/EclipseState/Grid/TransMult.cpp
- opm/parser/eclipse/EclipseState/Grid/TransMult.hpp
- opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/FaultTests.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/InitConfig/InitConfig.cpp
- opm/parser/eclipse/EclipseState/InitConfig/InitConfig.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
- opm/parser/eclipse/IntegrationTests/TransMultIntegrationTests.cpp
- opm/parser/eclipse/Parser/Parser.cpp
Four commits.  Work on EclipseState and EclipseGrid
* Removed all dependency on `shared_ptr<Deck>` for EclipseState and EclipseGrid.
* Kept constructors for now, but mark them as deprecated.
* Made NNC a member instead of a shared_ptr.
* Made FaultCollection a raw member of EclipseState, with all Faults being kept in FaultCollection
* Replaced method `addFault(fault)` with `addFault(faultName)` (a string)
* Minor maintenance of InitConfig: moved initialization of primary types to header file.
Needs to be applied as well: OPM/opm-simulators#676
> Removed dependency on shared_ptr for deck and faults

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
- opm/parser/eclipse/IntegrationTests/IOConfigIntegrationTest.cpp
- opm/parser/eclipse/Parser/ParseContext.cpp
- opm/parser/eclipse/Parser/ParseContext.hpp
- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/Parser.hpp
ParseContext is member of state, allowing for default constructor
* ParseContext is now a true member of EclipseState
* ParseContext is copied into EclipseState so we no longer share reference
* Constructor now has default ParseContext argument
* Updated tests to reflect this, removed a test that checked ref equality
* Added static methods for Parser for constructing grid and state
* Added new ParseContext MISSING_SECTIONS with which we cannot construct state
* parse functions take ref over shared_ptr.  removed duplicate comment
> Parser::parse functions and ParseContext is member of state, allowing for default constructor

- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
Will check the deck for `ACTNUM` keyword when creating an `EclipseGrid` based on `Deck`. This is how the implementation until recently, and will work nicely in many cases. However - manipulations of `ACTNUM` beyond one global assignment - will be silently ignored.
See also comment in EclipseGrid.cpp
> Check deck for ACTNUM keyword.

- opm/parser/eclipse/Deck/DeckKeyword.cpp
Replaces error message `"Not a data keyword ?"` with `"Not a data keyword "KEYWORD"?"`
> Throw now contains name() of deckKeyword

- opm/parser/eclipse/IntegrationTests/CMakeLists.txt
Is this sufficient for adding SPE9_CP_GROUP as a test case for the parser?
How can I run the test?
> Add SPE9_CP_GROUP as test case for the parser

- opm/parser/eclipse/EclipseState/EclipseState.hpp
With the introduction of Parser::parse methods and the relaxed lifetime
requirement of Deck (i.e. users no longer need to keep a Deck instance
around for EclipseState to be considered valid), the UnitSystem cannot
be a reference, but must rather be stored.
Since the unit system is immutable once the deck is read this is
unproblematic. It's also small and cheap to copy.
> EclipseState stores copy of Deck's UnitSystem

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Grid/NNC.cpp
- opm/parser/eclipse/EclipseState/Grid/NNC.hpp
- opm/parser/eclipse/IntegrationTests/NNCTests.cpp
* The NNC in the eclipse state is and will always be the nnc from deck
* updated tests
Depends on
* OPM/opm-simulators#680 which in turn depends on
* OPM/opm-output#27
> Renamed getNNC() to getInputNNC() avoids confusion

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
Allow clients to query time as time_t, not boost::posix::ptime
> Support Schedule::posixStartTime()

- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
Occasionally the SUMMARY section requests wells or groups that aren't
defined in the Deck. Ignore these names (which would typically crash
downstream) and carry on.
> Split Well/Group; ignore unknown names

- CMakeLists.txt
- opm/json/tests/CMakeLists.txt
- opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
- opm/parser/eclipse/EclipseState/Schedule/MSW/SegmentSet.cpp
- opm/parser/eclipse/EclipseState/Tables/TableColumn.cpp
- opm/parser/eclipse/Generator/KeywordGenerator.cpp
- opm/parser/eclipse/Generator/KeywordLoader.cpp
- opm/parser/eclipse/Parser/tests/CMakeLists.txt
- opm/parser/eclipse/RawDeck/RawKeyword.cpp
- opm/parser/eclipse/RawDeck/StarToken.hpp
`ssize_t` is included using `<ert/util/ssize_t.h>` On Linux, this will end up with include of `<sys/types.h>`
This PR will fix most of compiler issues on VS2015. The compiler issue related to
```C++ 
this->keywords = fun::concat( fun::map( handler, section ) );
```
will be handled in a separate PR.
See link below for closed (and not merged) PR and commit related to fun::concat issue
https://github.com/OPM/opm-parser/pull/811/commits/d6bd4485b0daef9d397e94f652c157db505c0778
> VS2015 compiler fixes

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
- opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
Removed EclipseGrid::EclipseGrid( ecl_grid_type * )
Tiny steps towards fully functional C++ value semantics.
> EclipseGrid copy constructor.

- opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
- opm/parser/eclipse/EclipseState/Tables/VFPProdTable.cpp
- opm/parser/eclipse/EclipseState/Tables/VFPProdTable.hpp
These VFP messages should really go into debug files, that's not useful for the user.
```
VFPPROD bhp versus thp not monotonic increasing: 7/4224(0%) elements failed test
VFPPROD bhp versus thp not monotonic increasing: 9/3168(0%) elements failed test
VFPPROD bhp versus thp not monotonic increasing: 1/7296(0%) elements failed test
VFPPROD bhp versus thp not monotonic increasing: 6/15200(0%) elements failed test
VFPPROD bhp versus thp not monotonic increasing: 5/13300(0%) elements failed test
VFPPROD bhp versus thp not monotonic increasing: 11/13300(0%) elements failed test
VFPPROD bhp versus thp not monotonic increasing: 8/13300(0%) elements failed test
VFPPROD bhp versus thp not monotonic increasing: 10/13300(0%) elements failed test
VFPPROD bhp versus thp not monotonic increasing: …
```
> Write the VFP testing information into Debug file.

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/EclipseConfig.cpp
- opm/parser/eclipse/EclipseState/EclipseConfig.hpp
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
This PR cleans up some dependencies and intricacies in the `EclipseState` constructor and how the members depend on each other.  We do this by introducing a container class `EclipseConfig`.
* The API exposed by Parser (`EclipseState`) is unchanged as of now
* This class contains the following State members with methods
- `m_ioConfig` and `getIOConfig` as well as `getIOConfigConst`
- `m_initConfig` and `getInitConfig`
- `m_simulationConfig` and `getSimulationConfig`
- `m_summaryConfig` and `getSummaryConfig`
* Got rid of awkward `initIOConfigPostSchedule` function (and corresponding call)
* For better decoupling
* For future, ease the shared_ptr-ref transition
> Introducing EclipseConfig -- a container class

- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
I have tested several proposed solutions based on input from @jokva, but unfortunately I was not able to fix the compiler issue in any other way than suggested here. As I have mentioned earlier, I do not have much experience with newer c++, so it is likely there exists an easy solution I am not aware of.
To fix this issue in a different way than suggested here, I believe a developer with experience in this field working on VS2015 will be required.
> VS2015 : Workaround for VS2015 compiler bug

- jenkins/build-pr.sh
update build order, opm-output moved in the dependency tree
> update jenkins build scripts

- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/tests/ParserTests.cpp
Some decks use comma to separate items in a record, but the comma adds
no extra information and is essentially ignored. Post-process the file
after cleaning it and replace all commas with whitespace.
Considering the record "foo bar , , , baz" / baz will silently be moved
to the third item, but handling that situation is a **lot** more
difficult and time consuming and not worth the effort for now.
Additionally, we have yet to receive decks that fail in such a manner,
nor are we sure if it is even a valid record in Eclipse.
> Strip commas from the input deck

- CMakeLists.txt
- cmake/build_check.cmake
- cmake/config/opm_parser_build_config.hpp.in
- opm/parser/eclipse/Parser/tests/ParserIncludeTests.cpp
We have some tests checking symlink behavior - disable these tests if we don't have `symlink()`
> Check for symlink() and compile test conditionally

- opm/parser/eclipse/Parser/ParserKeyword.cpp
- opm/parser/eclipse/Parser/ParserKeyword.hpp
this fixes OPM/opm-simulators#702. which turned out to be a quirk of the
build system which is due to the fact that opm-parser likes to do some
things differently than the rest of OPM. (in this case the culprit was
that it does not generate a `config.h` file which resulted in the
HAVE_REGEX macro to be different between opm-parser and downstream
which in turn causes the ABI to be incompatible.)
Note that it would be nice to use `std::regex` instead of Boost, but
this is currently blocked by the requirement that the oldest supported
compiler is GCC 4.8. (GCC 4.8 only provides a stub implementation of
`std::regex`.)
> use boost::regex unconditionally

- opm/parser/eclipse/EclipseState/Schedule/Group.cpp
- opm/parser/eclipse/EclipseState/Schedule/Group.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well.hpp
- opm/parser/eclipse/EclipseState/Schedule/WellSet.cpp
- opm/parser/eclipse/EclipseState/Schedule/WellSet.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/GroupTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/WellSetTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/WellSolventTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/WellTests.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- opm/parser/eclipse/IntegrationTests/ParseWellWithWildcards.cpp
- opm/parser/eclipse/IntegrationTests/ScheduleCreateFromDeck.cpp
I'm doing some work on output that works with the parser, and I keep finding issues with the parser interface.
This patch set smooths some of the edges in the `Schedule` interface by making `Well` and `Group`-functions have uniform behaviour w.r.t. types. Since this soft-breaks the interface anyway, it's about time to retire `WellPtr` and friends.
Ideally I'd make the Well communication here a reference right away, but that would mean a lot of `->` to `.` changes, which is work for another day. By removing the ownership sharing (which was a ruse) from the interface, replacing `shared_ptr` with raw pointers, little changes in client code.
> Remove shared_ptr Well alias, make Schedule interface more consistent

- opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- opm/parser/eclipse/EclipseState/Eclipse3DProperties.hpp
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Grid/FaultCollection.cpp
- opm/parser/eclipse/EclipseState/Grid/FaultCollection.hpp
- opm/parser/eclipse/EclipseState/Grid/FaultFace.hpp
- opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
- opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
- opm/parser/eclipse/EclipseState/Grid/TransMult.cpp
- opm/parser/eclipse/EclipseState/Grid/TransMult.hpp
- opm/parser/eclipse/EclipseState/Grid/tests/MULTREGTScannerTests.cpp
- opm/parser/eclipse/IntegrationTests/ResinsightTest.cpp
In stabilizing the OPM-parser API, some minor modifications of internal parser API.
* removed unused `MULTREGTScanner` constructor argument
* removed `shared_ptr` usage in `MULTREGTScanner`
* reduced `shared_ptr` in `EclipseState` (`Section`, `GridSection`, `FaultCollection`, `TransMult`)
* some fixes in includes (removed unused, imported used, sorted)
We will soon remove shared pointers from the EclipseState API, but since that requires a larger synchronized PR, we will wait with that until the internal API seems more stable.  This PR contains just some of the internal modifications necessary that do not require downstream changes.
> Minor refactor. Changed shared_ptr to references in EclipseState and related objects

- opm/parser/eclipse/EclipseState/Grid/GridProperties.cpp
Functions from `<cmath>` are used without namespace and without including the header.
I guess these have leaked from other include files, but with gcc 6.1.1 I get compile errors.
> Add missing namespace and include file

- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
- opm/parser/eclipse/EclipseState/IOConfig/tests/IOConfigTest.cpp
The purpose of this PR is to get the combination of output path and basename as one variable; that can then be sent directly to e.g. the summary output routine.
> Added IOConfig::getOutputBase()

- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.hpp
- opm/parser/eclipse/Units/UnitSystem.cpp
- opm/parser/eclipse/Units/UnitSystem.hpp
Two convenince call for downstream users that allows querying well rates
with the assumption that if something is unsupported or of the wrong
type, return plain zero.
Adds the "identity" unit which is a no-op under to_si/from_si
conversion.
These are both features I find useful for downstream development.
> Improved well properties interface

- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
The IOConfig object is maybe not the perfect place for it - but that object is already mutable.
The purpose of this is to allow easier testing of INIT and EGRID files from flow, by allowing somthing like 'flow --nosim FILE.DATA'
> Moved NOSIM handling to IOConfig + allow override.

- opm/parser/eclipse/Deck/Deck.cpp
- opm/parser/eclipse/Deck/Deck.hpp
- opm/parser/eclipse/Deck/tests/DeckTests.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
This PR gives some love to the `SummaryConfig` internals and also adds a new feature to address https://github.com/OPM/opm-output/issues/57
Notable additions:
* `SummaryConfig` **no longer contains duplicate entries**.
* Some initialization list support for `Deck`
* Support for merging two `SummaryConfig` objects
* `SummaryConfig` internals refactored.
> [SummaryConfig] Refactoring & remove duplicate entries

- appveyor.yml
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/tests/IOConfigTest.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
- opm/parser/eclipse/Generator/tests/KeywordLoaderTests.cpp
- opm/parser/eclipse/IntegrationTests/IncludeTest.cpp
Appveyor http://appveyor.com/ is a CI service for Windows. Since parser is meant to be Windows compatible we need this feature. Like travis and gitlab, it is driven by an yml file.
In addition, this PR fixes tests that break on Windows.
> Appveyor support

- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
- opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
With this PR the EclipseGrid::fwriteEGRID() method is removed; writing is initiated and handled in the opm-output module.
> Remove EclipseGrid::fwriteEGRID()

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
**BEHAVIOURAL CHANGE**
The "soft" change here is that instead of simply accepting well names or * for well identifiers in the Completion family of summary keywords, patterns are accepted. This covers the documented behaviour *and more*, so hopefully everyone are pleased.
The more radical change, however, is  the modification to the well matching algorithm. It **used** to expand and check wild cards (denoted by *) and then include every well matching, returning possibly the empty list. However, when looking up a well by name (a set pattern, if you will) it would *throw* if the well wasn't found. This has been changed to, in the case of an invalid well name, returning an empty list.
This is consistent to the matching behaviour, but some code (in particular WELTARG) relied on the throwing …
> Well matching returns empty list when no wells are found; Summary/Completion use Well matching

- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
The W-family of keywords accept a pattern to expand, rather than just
names or defaulted-all. This is the actual behaviour, according to the
manual.
> [Summary] W-keywords accept patterns

- opm/parser/eclipse/Units/UnitSystem.cpp
- opm/parser/eclipse/Units/UnitSystem.hpp
Extends unit system support by adding three new units, all ratios, which are non-scaling. The more major feature is the ability to look up a string representation of the unit (M, M3, KG, FT, BARSA etc) from a `measure`.
The need is largely driven from opm-output.
> Unit system unit name

- opm/parser/eclipse/Applications/opmi.cpp
- opm/parser/eclipse/EclipseState/EclipseConfig.cpp
- opm/parser/eclipse/EclipseState/EclipseConfig.hpp
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Grid/tests/ADDREGTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/CopyRegTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/EqualRegTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/MultiRegTests.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/PORVTests.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
- opm/parser/eclipse/EclipseState/IOConfig/tests/IOConfigTest.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
- opm/parser/eclipse/IntegrationTests/BoxTest.cpp
- opm/parser/eclipse/IntegrationTests/EclipseGridCreateFromDeck.cpp
- opm/parser/eclipse/IntegrationTests/IOConfigIntegrationTest.cpp
- opm/parser/eclipse/IntegrationTests/ParseMULTREGT.cpp
- opm/parser/eclipse/IntegrationTests/ParseTOPS.cpp
- opm/parser/eclipse/IntegrationTests/TransMultIntegrationTests.cpp
- opm/parser/eclipse/Parser/Parser.cpp
Remove returning of shared_ptr.  The opm-parser and opm-output are moving towards a shared_ptr-free state (except from the cases where we actually use shared ownership)
* TransMult, InitConfig, SimulationConfig are now returned as references, and not as shared_ptr's.
* The method `applyModifierDeck` takes a reference, not shared_ptr
This PR has downstream dependencies:
* OPM/opm-output#73
* OPM/opm-core#1056
* OPM/opm-simulators#783
* OPM/ewoms#63
> Removing some use of shared_ptr

- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
- opm/parser/eclipse/Units/ConversionFactors.hpp
This contains two commits which were done to target unused variable compiler warnings.
- One commit which moves unit-conversion constant generation to compile time. Constexprs can be unused and safely pruned from the binary by the optimizer. There is equivalent code in opm-core for this, i did not target that one as i'm not entirely sure what the deal with the duplication is about.
- a trivial removal of some unsed references in some tests.
> Quell some compiler warnings

- opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp
That constructor is not available in C++11, only from C++14 on.
(Causes compile error with -std=c++11 for me.)
> Do not use constexpr pair constructor.

- opm/parser/share/keywords/000_Eclipse100/M/MULTREGP
it is parsed and put into the deck, but it is not internalized in any
way. (Note that, given that this keyword is quite simple, adding
sophisticated code to absorb it into EclipseState would be overkill
in my not so humble opinion.)
> add bare-bones support for the MULTREGP keyword

- opm/parser/eclipse/Units/ConversionFactors.hpp
- opm/parser/eclipse/Units/UnitSystem.cpp
- opm/parser/eclipse/Units/UnitSystem.hpp
- opm/parser/eclipse/Units/tests/UnitTests.cpp
This commit adds conversion factors for the ECL LAB unit conventions--notably Atmospheres for pressures, Hours for time, Grams for mass, and cubic centimetres for volumes.
I am not sure if the unit names in [`lab_names`](https://github.com/OPM/opm-parser/blob/ba69320b528d20aabeff0a5f061495a3eb962428/opm/parser/eclipse/Units/UnitSystem.cpp#L226-L246) match those of ECL, but this is my best suggestions at present.
On a second note, if I may be so bold as to suggest an interface change, I'd propose that the `UnitSystem::new*()` constructor methods at some point be modified to return either `std::unique_ptr<>`s or even objects by value.
> UnitSystem: Add skeleton implementation of LAB conventions

- opm/parser/eclipse/RawDeck/StarToken.cpp
The hand-written number parser functions implemented using strtod and
friends were rather slow (profiling indicates that typically 30% of the
program is spent inside of strtod internals). By using
boost::spirit::qi, which we already depend on through boost-filesystem
and others this portion typically seem to be reduced to 20% (via
instruction count) and with somewhat better cache performance.
Rudimentary measuring indicates ~15% speedup overall.
Additionally, the intention is a lot clearer this way, so readability
received a boost. Compilation time of StarToken goes through the roof.
> Replace number parser with boost::spirit::qi

- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
With this PR we will not at all apply the MAPEXES transform when creating the EclipseGrid / simulation grid. However - if a MAPAXES is specified in the input deck that will be retained, and written out to disk when the EGRID file is saved again.
Depends on: https://github.com/Ensembles/ert/pull/1221
Unless something pops up I intend to merge this - and https://github.com/Ensembles/ert/pull/1221 together on monday.
> Do not apply the MAPAXES transform.

- opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- opm/parser/eclipse/EclipseState/Grid/tests/PORVTests.cpp
This PR implements full support for the MULTREGP keyword. It tries to faithfully implement the documented ECLIPSE bugs w.r.t. this keyword, but lacking the real thing, I cannot check if MULTREGP is considered when removing cells due to MINPV. (I assume that it is considered, but somebody should check to make sure.)
Finally, for this to be consistent within `flow`, the simulator must retrieve the pore volume of the active cells from opm-parser (i.e., it requires a small patch for opm-simulators).
> Implement support for MULTREGP

- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
This is for all practial purposes: #916 - have just rephrased the comment which seems to indicate that `input_vector.size() == numActive` is a special case.
Will self merge,
> Return identity when compressing active-only cells.

- opm/parser/eclipse/EclipseState/Grid/tests/EclipseGridTests.cpp
the simpler fix would be to make ```i``` size_t, but i figured it may as well use the stl function.
> quell signed/unsigned comparison warning

- opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
- opm/parser/eclipse/EclipseState/Schedule/Group.cpp
- opm/parser/eclipse/EclipseState/Schedule/Group.hpp
- opm/parser/eclipse/EclipseState/Schedule/GroupTree.cpp
- opm/parser/eclipse/EclipseState/Schedule/GroupTree.hpp
- opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.cpp
- opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.hpp
- opm/parser/eclipse/EclipseState/Schedule/Tuning.cpp
- opm/parser/eclipse/EclipseState/Schedule/Tuning.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/GroupTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/TuningTests.cpp
- opm/parser/eclipse/IntegrationTests/ScheduleCreateFromDeck.cpp
Removes most shared_ptr members from the Schedule class. Some other changes are mandated by this:
* `DynamicState::get` returns a *reference*, not a value copy. This has implications for `std::vector<bool>` which can't have its `at` returned by reference since it would be a temporary. All `DynamicState<bool>` are instead represented by `int`, and appropriate bool conversions are added.
* `OilVaporizationProperties` has its default constructor public, but the default constructed version will be `UNDEF` and comparing to this will always be `false`.
* GroupTree has a copy constructor that maps to `GroupTree::deepCopy`.
> Remove shared ptrs from schedule

- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.hpp
The new Well::getCompletions( ) method without argument will return all
the existing completions at the end of the simulation.
> Added Well::getCompletions( ).

- CMakeLists.txt
this is handled by FindCXX11Features
> fixed: do not manually add std=c++0x to cxx flags

- opm/parser/eclipse/Parser/Parser.cpp
The termination logic would sometimes need to scan the full line to see
if some terminating condition was found inside quotes. Plenty of
comments in a file start on the first character of a line, meaning this
scan is unnecessary.
> Short circuit when line terminator is found first

- opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
for some reason, it looks like `std::find_if()` does not work on
ubuntu 16.10 with clang and enabled optimizations. since as far I can
see this 'if' is a minor performance improvement in non-time critical
code, let's just remove the condition.
> fix the PORV grid property for clang with optimizations

- opm/parser/eclipse/EclipseState/Schedule/MessageLimits.cpp
- opm/parser/eclipse/EclipseState/Schedule/MessageLimits.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/CMakeLists.txt
- opm/parser/eclipse/EclipseState/Schedule/tests/MessageLimitTests.cpp
1. Will retain already set values when only some items are set.
2. Will parse the sections before the SCHEDULE section to create a
correctly initialized MessageLimits object.
> Changes to MessageLimits:

- opm/parser/eclipse/Units/UnitSystem.hpp
- opm/parser/eclipse/Units/tests/UnitTests.cpp
Currently on a warning-hunt to clean up the sources before the release. Encountered this:
```
/Users/atgeirr/opm-build-release/opm-parser/opm/parser/eclipse/Units/tests/UnitTests.cpp:176:79: warning: 
all paths through this function will call itself [-Winfinite-recursion]
inline std::ostream& operator<<( std::ostream& stream, const UnitSystem& us ) {
^
```
This is not a false positive, although this operator has not been triggered since the tests succeed. The root cause is the lack of `explicit` making the UnitSystem constructor implicitly converting. After adding that, an explicit cast to int is also needed for the operator<<. (I assumed that is the behaviour sought.)
> Make constructor explicit, fix operator<<.

- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/IntegrationTests/ScheduleCreateFromDeck.cpp
- opm/parser/share/keywords/000_Eclipse100/W/WCONINJE
- opm/parser/share/keywords/000_Eclipse100/W/WSEGITER
- opm/parser/share/keywords/001_Eclipse300/G/GCONPROD
This is a PR looking for suggestion. 
In our model, we need to handle some statement like the following when using group control. 
```
WCONINJE
'INJE1' 'WATER' 'OPEN' 'GRUP' /
/
```
With the current implementation, basically, it gives no control for the well `INJE1` now. And the results from Eclipse strongly suggest that they use the defaulted BHP limit value ( `6803 atma, or 1.0E5 psia, or 6895 barsa`). That means the defaulted BHP limit always work there.
Please help to suggest if the current proposal works or we should do it in some different way. We got the desired result with this PR. 
BTW: I am not sure what unit system we should use when specify default value in the keyword definition. I saw previous value is 6891, I assume it was barsa there. Please correct me if I was wrong.
> Always applying the BHP limit from WCONINJE.

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
- opm/parser/eclipse/EclipseState/Runspec.cpp
- opm/parser/eclipse/EclipseState/Runspec.hpp
- opm/parser/eclipse/EclipseState/Schedule/Group.cpp
- opm/parser/eclipse/EclipseState/Schedule/Group.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp
- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleEnumTests.cpp
- opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
- opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
- opm/parser/eclipse/EclipseState/tests/CMakeLists.txt
- opm/parser/eclipse/EclipseState/tests/EclipseStateTests.cpp
- opm/parser/eclipse/EclipseState/tests/RunspecTests.cpp
Runspec object; move phases from TableManager
There has never really been a natural home for initial properties that
aren't InitConfig, meaning information such as phases in the deck and
other runspec information hasn't had a natural home.
This patch introduces the Runspec object on EclipseState for phase
information and other similar properties that are interesting and static
for when setting up parameters etc. for simulation, that aren't all that
interesting once simulation starts.
An additional benefit is a leaner implementation for the phase enum and
some stricter semantics via enum classes.
> Phase information and runspec

- opm/parser/eclipse/CMakeLists.txt
The ahead-of-time JSON-to-C++-object compilation step does not need all
the source files as it was passed. Reduces the set of source files
compiled into the createKeywordList binary to just the files it needs.
> Only give needed source files to createKeywordList

- opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/GroupTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/WellSetTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/WellTests.cpp
Simply flatten the Well class by removing all internal shared_ptrs. PR also includes the following minor changes:
* A bugfix in DynamicState, making the `find` method const
* TimeMap is not a member in `Well` as only its size was used, which is what we're now storing.
> Remove shared ptr members well

- opm/parser/eclipse/Deck/DeckItem.cpp
- opm/parser/eclipse/Deck/DeckItem.hpp
DeckItem.push_back using insert for 1 element turns out to be very
expensive and caused a performance degredation.
> DeckItem.push_back overload for size = 1

- opm/parser/eclipse/EclipseState/Schedule/DynamicVector.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/DynamicVectorTests.cpp
Topic says it all, really, just a simplification of the implementation of DynamicVector. The old implementation was largely oriented around storing `shared_ptr`s, which doesn't apply as much anymore.
> Simplified DynamicVector implementation

- opm/parser/eclipse/EclipseState/Schedule/GroupTree.cpp
This PR fixes the follwoing warnings that I got with gcc:
```
/home/mblatt/src/dune/opm/opm-parser/opm/parser/eclipse/EclipseState/Schedule/GroupTree.cpp: In member function ‘void Opm::GroupTree::update(const string&, const string&)’:
/home/mblatt/src/dune/opm/opm-parser/opm/parser/eclipse/EclipseState/Schedule/GroupTree.cpp:39:76: warning: declaration of ‘parent’ shadows a member of 'this' [-Wshadow]
void GroupTree::update( const std::string& name, const std::string& parent ) {
^
/home/mblatt/src/dune/opm/opm-parser/opm/parser/eclipse/EclipseState/Schedule/GroupTree.cpp: In member function ‘std::vector<std::basic_string<char> > Opm::GroupTree::children(const string&) const’:
/home/mblatt/src/dune/opm/opm-parser/opm/parser/eclipse/EclipseState/Schedule/GroupTree.cpp:76:77: warning: …
```
> Fixes warning about parameters shadowing members of this.

- jenkins/build.sh
- opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
opm-grid moved in the dependency graph. also has a commit that removes an unused variable i now noticed. i can remove if you want.
> Update jenkins downstream list

- opm/parser/eclipse/EclipseState/Schedule/Completion.cpp
- opm/parser/eclipse/EclipseState/Schedule/Completion.hpp
- opm/parser/eclipse/EclipseState/Schedule/CompletionSet.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/CompletionSetTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/CompletionTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/WellTests.cpp
Connections are given a completion number starting at 1 implicitly when
they're first defined by the COMPDAT keyword. Until now this number has
been ignored.
The number itself isn't *used* for anything with this patch, just stored
and accessible.
> Register completion number from COMPDAT

- opm/parser/eclipse/Units/UnitSystem.cpp
- opm/parser/eclipse/Units/tests/UnitTests.cpp
The FIELD units don't use identity in their converison from SI, as the
unit is Mscf/stb rather than m3/m3.
Should fix https://github.com/OPM/opm-output/issues/146
> Correct unit for Field gas-oil+oil-gas ratio

- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/GeomodifierTests.cpp
- opm/parser/eclipse/EclipseState/Util/OrderedMap.hpp
- opm/parser/eclipse/IntegrationTests/TransMultIntegrationTests.cpp
Now that WellSet and GroupTree have been modified to no longer use internal references, we can make the Well object copyable and store it directly in the Schedule object.
> Make Well+Schedule copyable

- opm/parser/eclipse/Units/tests/UnitTests.cpp
These have been copied from opm-core, where they are scheduled to be removed (since the unit handling moved to opm-parser).
> Add some tests for the unit constants.

- opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
- opm/parser/eclipse/EclipseState/Schedule/Group.cpp
- opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.cpp
- opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/WellInjectionProperties.cpp
- opm/parser/eclipse/EclipseState/Schedule/WellInjectionProperties.hpp
- opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp
- opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/DynamicStateTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/GroupTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/WellTests.cpp
This PR fixes a couple of bugs unearthed by the main effort - simplify the `DynamicState` implementation (or rather multiple aspects of it).
The *big* change here is the last commit:
> Changes DynamicState's implementation to, instead of maintaining a
> current and initial element, rely on std::vector's capabilities. This
> introduces a small change in semantics.
> 
> The new DynamicState will up-front allocate a vector of TimeMap.size,
> and all entries will be the initial value. Lookup is then simplified to
> vector.at. DynamicState.update will assgin to the given index and *all
> consecutive elements* which will enforce the same invariant as before.
>
> The behavorial change is that DynamicState will no longer throw on
> update(x); update(y); where y < x. Instead, the resulting effect …
> Remagine DynamicState

- opm/parser/eclipse/Parser/createDefaultKeywordList.cpp
Work around a weakness of older boosts by forcing C locale if
std::locale throws.
The real solution is to not have broken locales, but this should make it
slightly easier to get the JSON keywords compiled.
Addresses https://github.com/OPM/opm-parser/issues/973
Please note that this does not fix unit tests, it does not fix opmi and it does not fix flow, because it's really up to the driver application to handle this.
A sufficiently new boost, properly configured locales or `LC_ALL="C" make` should also solve this problem.
> Don't crash keyword compilation on broken locales

- opm/parser/eclipse/EclipseState/Grid/FaceDir.cpp
This has been encountered in the wild. We treat it like the documented 'X', 'I' etc. strings.
> Allow 'X+', 'I+', 'Y+', 'J+', 'Z+' and 'K+' for FaceDir strings (in FAULTS)

- opm/parser/eclipse/EclipseState/Schedule/Completion.cpp
- opm/parser/eclipse/EclipseState/Schedule/CompletionSet.cpp
- opm/parser/eclipse/EclipseState/Schedule/CompletionSet.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/ScheduleTests.cpp
- opm/parser/eclipse/EclipseState/Schedule/tests/WellTests.cpp
Support for COMPLUMP. a keyword to re-assign completion numbers that can
be used with keywords such as WELOPEN.
Some helper functions were moved out of handleWELOPEN and reused in
handleCOMPLUMP.
Built on top of https://github.com/OPM/opm-parser/pull/995 and https://github.com/OPM/opm-parser/pull/996
> COMPLUMP support

- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- opm/parser/eclipse/EclipseState/Grid/GridDims.cpp
With C++14 the warnings generated will probably disappear, but for now this keeps clang happy (warning-free).
> Add extra braces for C++11 compilers.

- opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
- opm/parser/eclipse/EclipseState/tests/Eclipse3DPropertiesTests.cpp
This removes occurences of the anti-pattern of moving the return value. This prevents compile warnings on new compilers (at least clang), is simpler to read and understand, and can be faster.
> Remove pessimizing move() in return statements.

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/Tables/JFunc.cpp
- opm/parser/eclipse/EclipseState/Tables/JFunc.hpp
- opm/parser/eclipse/EclipseState/Tables/SgfnTable.hpp
- opm/parser/eclipse/EclipseState/Tables/SgofTable.hpp
- opm/parser/eclipse/EclipseState/Tables/SimpleTable.cpp
- opm/parser/eclipse/EclipseState/Tables/SimpleTable.hpp
- opm/parser/eclipse/EclipseState/Tables/SlgofTable.hpp
- opm/parser/eclipse/EclipseState/Tables/SwfnTable.hpp
- opm/parser/eclipse/EclipseState/Tables/SwofTable.hpp
- opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
- opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
- opm/parser/eclipse/EclipseState/Tables/Tables.cpp
- opm/parser/eclipse/EclipseState/Tables/tests/TableContainerTests.cpp
- opm/parser/eclipse/EclipseState/Tables/tests/TableManagerTests.cpp
- opm/parser/eclipse/IntegrationTests/ParseSGOF.cpp
- opm/parser/eclipse/IntegrationTests/ParseSLGOF.cpp
- opm/parser/eclipse/IntegrationTests/ParseSWOF.cpp
* Fully internalized the JFUNC keyword into class `JFuncTable.hpp`
* Added JFUNC flag, `getJFuncColumn()` and `getJFuncTable()` in TableManager
* added protected member m_jfunc to SimpleTable
* Added getJFuncColumn to accompany getPcowColumn
* Throws if pressure or jfunc is accessed inappropriately
* ... meaning if getPcowColumn is called when JFUNC is in deck, or
* getJFuncColumn is called when JFUNC is not in deck
* added tests for throwing and for getJFuncColumn
* In the event that one tries to get "PCOW" or "PCOG" via getColumn
* ... this will throw if JFUNC is present in the deck.
* Added tests.
> Fully internalized the JFUNC keyword

- opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.cpp
- opm/parser/eclipse/EclipseState/Schedule/Well.hpp
- opm/parser/eclipse/EclipseState/Schedule/tests/WellTests.cpp
- opm/parser/eclipse/EclipseState/tests/Eclipse3DPropertiesTests.cpp
- opm/parser/share/keywords/000_Eclipse100/A/AITS
- opm/parser/share/keywords/000_Eclipse100/R/ROCKNUM
- opm/parser/share/keywords/000_Eclipse100/W/WPAVEDEP
Commit 1.  Implements `operator==` and `operator!=` for `Well`.
Commit 2.  Parser now handles `AITS` (but ignores it).
Commit 2.  Internalize `ROCKNUM` and added test.
> Skip AITS and ROCKNUM

- CMakeLists.txt
This adds `BUILD_SHARED_LIBS` as a `CMake` option so it is possible to toggle in `ccmake`.
> added BUILD_SHARED_LIBS to option in cmake

- opm/parser/eclipse/CMakeLists.txt
- opm/parser/eclipse/EclipseState/EndpointScaling.cpp
- opm/parser/eclipse/EclipseState/EndpointScaling.hpp
- opm/parser/eclipse/EclipseState/Runspec.cpp
- opm/parser/eclipse/EclipseState/Runspec.hpp
- opm/parser/eclipse/EclipseState/tests/RunspecTests.cpp
In liue of the [comment]( https://github.com/OPM/opm-parser/pull/1020#pullrequestreview-14974521) I have concluded that I merged #1020 a bit prematurely, as @andlaus commented the methodname `Runspec::endpoint_scaling()` is quite different from the main pattern in opm-parser.
Personally I find this a quite difficult subject to weigh down on.
1. A consistent codebase is obviously easier for everyone to navigate, and the information implicitly conveyed in a consistent codebase will catch bugs before they happen. 
2. Being a developer is a form of creative work - we are nearly artists; and I guess the freedom to make such slightly arbitrary choices like `Runspec::endpoint_scaling()` versus `Runspec::endpointScaling()` is valued by many of us. As developers we also change and mature; and it …
> Endscale rename

- opm/parser/eclipse/EclipseState/Eclipse3DProperties.hpp
As far as I can tell (except in ResInsight), the function `Eclipse3DProperties.getRegion(deckitem)` is not used _outside `Eclipse3DProperties`._
Made it private.
> Made getRegion() in e3d private

- opm/parser/eclipse/Parser/Parser.cpp
- opm/parser/eclipse/Parser/tests/ParserTests.cpp
- testdata/parser/PATHSWithBackslashes.data
- testdata/parser/include/foobackslash.inc
The following addresses #1033 by converting backslashes in include path strings to slashes. This is done after all other processing such as expanding mapped paths (of the `$PATH_KEY` kind), just before creating the boost::filesystem::path object.
I believe it is a better solution than using a conversion script since:
- requiring such a script is likely to reduce usage by casual users (it doubles the number of commands to remember...)
- writing such a script in such a way that it only does what it is supposed to do might be hard, the current solution can only affect INCLUDE paths
- we can (and do) give a warning about this, so that users can choose to make the paths universal (using slashes) but do not require it
@hnil can you verify that this PR solves the observed problem?
> Replace backslash in INCLUDE paths

- opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
- opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
this object corresponds to the EQLDIMS keyword. Probably it is not the most intuitive place to provide access to this keyword, but as far as I can see, the table manager is the only place where this object is already properly instantiated.
> TableManager: export the Eqldims object

- appveyor.yml
opm-common now has a `#include <unistd.h>` which breaks the build on windows.
> Do not build opm-common on Windows.

- debian/rules
needed for python-cwrap find rule.
Backport from release branch.
> explicitly specify /usr as a prefix path in packaging

- CMakeLists.txt
while packaging 2017.04, i realized opm builds with -mtune=native by default. this is not a good idea in generic binaries, as you end up tuning to whatever hardware happens to be available on the build slave.
in general, the option is attached to a cmake option (which defaults to true). that means i could disable it.
in opm-parser build optimization flags are more rigid, so the release is built with native tuning.
this enables the generic opm-common hosted rule to allow proper builds in the future. it should not alter anything by default (maybe order and such but the actual flags being enabled should be the same). please help me verify the last point - it's the same on my box but that's no proof.
> changed: use the common functionality for optimization flags

- opm/parser/eclipse/EclipseState/EndpointScaling.cpp
```
opm-parser/opm/parser/eclipse/EclipseState/EndpointScaling.cpp: In constructor ‘Opm::EndpointScaling::EndpointScaling(const Opm::Deck&)’:
/opm-parser/opm/parser/eclipse/EclipseState/EndpointScaling.cpp:102:14: warning: declaration of ‘reversible’ shadows a member of 'this' [-Wshadow]
bool reversible = true;
```
> Fixes shadowing member warning

- opm/parser/eclipse/EclipseState/EclipseConfig.cpp
- opm/parser/eclipse/EclipseState/EclipseConfig.hpp
- opm/parser/eclipse/EclipseState/EclipseState.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
- opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
- opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
- opm/parser/eclipse/EclipseState/Tables/tests/TableManagerTests.cpp
- opm/parser/share/keywords/000_Eclipse100/R/REGION_PROBE
The SUMMARY section keywords like `RPR` is used to ask for per region results. If the `Rxxx`keywords are given without region numbers the results should be reported *for all regions*:
```txt
RPR
/
```
currently the opm code interprets *all regions* as all FIPNUM values which are present in the grid, that could for instance result in the following set of summary keys: `{RPR:4, RPR:3, RPR:7}`. The Eclipse interpretation of *all regions* is the set `{"RPR:1, RPR:2, RPR:3, .... RPR:NTFIP}` - where `NTFIP`is the maximum number of fluid in place regions from either the `TABDIMS` or `REGDIMS` keyword. Observe that set of summary keys generated by Eclipse does not consider which regions are actually present in the deck, so we can get many summary variables which only get value zero.
I encourage …
> Summary rpr

- opm/parser/eclipse/EclipseState/SummaryConfig/tests/SummaryConfigTests.cpp
A unit test for the precense of "FOE" in summary config was created in SummaryConfigTests.cpp.
> Add unit test for field oil efficiency (aka FOE)

- lib/eclipse/EclipseState/Grid/EclipseGrid.cpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
- lib/eclipse/share/keywords/000_Eclipse100/D/DR
- lib/eclipse/share/keywords/000_Eclipse100/D/DRV
- lib/eclipse/share/keywords/000_Eclipse100/D/DTHETA
- lib/eclipse/share/keywords/000_Eclipse100/D/DTHETAV
- lib/eclipse/share/keywords/000_Eclipse100/I/INRAD
- lib/eclipse/share/keywords/000_Eclipse100/O/OUTRAD
- lib/eclipse/share/keywords/000_Eclipse100/P/PERMR
- lib/eclipse/share/keywords/000_Eclipse100/R/RADIAL
- lib/eclipse/share/keywords/001_Eclipse300/C/CIRCLE
- lib/eclipse/tests/EclipseGridTests.cpp
With this PR the EclipseGrid implementation has limited support for radial grids. The grid must be specified using the keywords `DRV, DTHETAV, DZV`and `TOPS`. When the radial grid is specified this way everything - including simulation and ouptut migth actually *Just Work*&trade;
> Basic support for cylindrical grids

- CMakeLists.txt
- lib/eclipse/CMakeLists.txt
This should ensure that non-standard boost library names are correctly forwarded to downstream modules.
> Create boost link targets dynamically.

- CMakeLists.txt
- appveyor.yml
- lib/eclipse/CMakeLists.txt
- lib/json/CMakeLists.txt
On some systems, in particular Windows or custom boosts, plenty
information about configuration is embedded into the library name.
However, opm-parser's boost names were hard coded to the vanilla library
names, which leads to libraries not being found.
Generate the target names dynamically (and address them as variables) so
that the target names match the name of the library actually being
linked to - a name which is also then later exported to the
opm-parser-config.cmake file.
Supersedes https://github.com/OPM/opm-parser/pull/1088
> Create boost targets names dynamically

- lib/eclipse/EclipseState/IOConfig/IOConfig.cpp
- lib/eclipse/EclipseState/Schedule/Schedule.cpp
- lib/eclipse/EclipseState/Schedule/TimeMap.cpp
- lib/eclipse/IntegrationTests/IOConfigIntegrationTest.cpp
- lib/eclipse/IntegrationTests/ScheduleCreateFromDeck.cpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.hpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
- lib/eclipse/tests/EclipseStateTests.cpp
- lib/eclipse/tests/ScheduleTests.cpp
- lib/eclipse/tests/TimeMapTest.cpp
Boost datetime internally uses a 32 bit integer type to represent time, and has a 2038 problem. 
In the opm-parser code the class `TimeMap` uses boost datetime internally, we intend to change that to `std::time_t` - which is a 64 bit integral type on any 64 bit linux, and also on any reasonably new 32bit linux.
The current PR will just change the `TimeMap::operator[]`to return `std::time_t` instead of boost datetime. The code still uses boost datetime internally.
Downstream:
ewoms: https://github.com/OPM/ewoms/pull/198
simulators: https://github.com/OPM/opm-simulators/pull/1222
> Change time map api

- lib/eclipse/EclipseState/Eclipse3DProperties.cpp
- lib/eclipse/share/keywords/000_Eclipse100/P/PERMTHT
- lib/eclipse/share/keywords/000_Eclipse100/R/RADIAL
- lib/eclipse/share/keywords/keyword_list.cmake
This change-set adds support for internalising the `PERMR` and `PERMTHT` keywords.  The former was already known to the parser, but was not recognised as a 3D grid property.  The latter is new as of this change-set.
We also relocate the `RADIAL` keyword to the `RUNSPEC` section as per the official specification.
> Support radial properties

- lib/eclipse/EclipseState/Eclipse3DProperties.cpp
- lib/eclipse/share/keywords/000_Eclipse100/P/PLMIXNUM
- lib/eclipse/share/keywords/keyword_list.cmake
the first patch changes the default value for the OPERNUM grid property from 0 to 1 and removes a `//*` token (which should be considered to be a *really* bad way to distinguish between C and C++).
the second patch adds the PLMIXNUM keyword and the corresponding grid property. this property would be good to have for the new implementation of the polymer blackoil extension: https://github.com/OPM/ewoms/pull/195#discussion_r122908138
> Add plmixnum

- configure
- dune.module
i.e. now it does not use anything from opm-common anymore even when it is build using dunecontrol.
this should make it quite a bit easier to use opm-parser stand-alone or as a upstream dependency for dune modules.
> make opm-parser fully independent of opm-common

- lib/eclipse/CMakeLists.txt
- lib/json/CMakeLists.txt
the exported file refers to imported targets through their
name with the expectation that these are defined whenever
the target file is included.
the use of custom imported targets for boost thus becomes
problematic in downstreams, since they are forced to define
these targets prior to opm-parser inclusion.
as the targets are named the same as their library
counterparts it appears to work per murphy's law.
cmake will simply fall back to interpreting the target names as
library names, e.g. it will do -lboost_filesystem.
there are two ways to fix this: either through manually
writing a opm-parser-config.cmake file which defines the boost targets,
then includes the target file, or by forgoing the use of targets for
the linking. 
i have here done the latter.
> changed: avoid use of targets for exports

- lib/eclipse/EclipseState/Schedule/Schedule.cpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- lib/eclipse/tests/ScheduleTests.cpp
The new Schedule::getWells( group, time) overload will recursively scan
th group tree rooted at 'group' and return all the wells in that tree.
> Added Schedule::getWells( group, time) overload

- lib/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
Correctly sort the smspec nodes when configuring summary files. Fixes several issues when the summary files generated by OPM are viewed with third-party applications. 
**Update**: intend to merge this on Friday 11.th of August - building of opm-parser will then require: https://github.com/Statoil/libecl/pull/146
> Sort SummaryConfig with smspec_node_cmp( ).

- CMakeLists.txt
There have been various occasions where having this information would have been useful for debugging.
> Added status message about the location of ecl.

- lib/eclipse/Deck/Deck.cpp
- lib/eclipse/include/opm/parser/eclipse/Deck/Deck.hpp
Copying Decks caused the first and last iterators in DeckView to point
to invalid memory.
> Added Deck copy constructor

- lib/eclipse/Deck/DeckItem.cpp
Build broke on latest Debian stable with introduction of std::fabs in https://github.com/OPM/opm-parser/pull/1120 This restores build.
> Added include on cmath to restore build on Debian.

- CMakeLists.txt
This brings default build options of opm-parser in line with the other opm-modules.
> Make Release the default build type rather than Debug

- lib/eclipse/EclipseState/EclipseConfig.cpp
- lib/eclipse/EclipseState/EclipseState.cpp
- lib/eclipse/EclipseState/Grid/NNC.cpp
- lib/eclipse/EclipseState/Grid/TransMult.cpp
- lib/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/EclipseConfig.hpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/EclipseState.hpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Grid/NNC.hpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Grid/TransMult.hpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- lib/eclipse/tests/SummaryConfigTests.cpp
- lib/eclipse/tests/TransMultTests.cpp
Minor refactoring of EclipseState constructor. To prepare for external Schedule.
Depends on: 
https://github.com/OPM/opm-output/pull/204
https://github.com/OPM/opm-core/pull/1176
> EclipseState: refactor constructor

- CMakeLists.txt
Previously only ecl/build was considered during the search. Now the subdirectory name can be arbitrary. One can also use a common build root (/path/to/build_root/{ecl|opm-parser}) located somewhere else.
This change is in line with the other OPM modules.
> OPMify sibling search for ecl.

- lib/eclipse/EclipseState/Schedule/Schedule.cpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- lib/eclipse/tests/ScheduleTests.cpp
- lib/eclipse/tests/integration/ScheduleCreateFromDeck.cpp
Do not shut well if all completions are shut using WELOPEN, but new
completions are opened using COMPDAT
> Fix shut well logic when WELOPEN and COMPDAT is combined

- lib/eclipse/Deck/Deck.cpp
- lib/eclipse/Units/UnitSystem.cpp
- lib/eclipse/include/opm/parser/eclipse/Units/UnitSystem.hpp
- lib/eclipse/include/opm/parser/eclipse/Units/Units.hpp
- lib/eclipse/share/keywords/000_Eclipse100/L/LAB
- lib/eclipse/share/keywords/000_Eclipse100/P/PVT_M
- lib/eclipse/share/keywords/keyword_list.cmake
- lib/eclipse/tests/ParserTests.cpp
- lib/eclipse/tests/UnitTests.cpp
The PVT-M unit convention is essentially the same as the Metric collection, except that pressure values are measured in atmospheres rather than bars.
> UnitSystem: Add Support for PVT-M Unit Conventions

- CMakeLists.txt
This allows to configure with-DCMAKE_INSTALL_PREFIX and find the installed version and not the build tree of ecl (that was used the last time).
I just did an installation test with `-DSIBLING_SEARCH=Off -DCMAKE_INSTALL_PREFIX=/path/to/install` and had a hard time figuring out why opm-parser still found the sibling build of ecl and not the installed version. Well there is still the package registry lying around as ecl is using it...
This is for discussion. One can also either explicitly set ecl_DIR (not tested) or set CMAKE_PREFIX_PATH (tested) to the installed version. But this seems more complicated than needed for users/admins.
> First try to find ecl with deactivated package registry.

- CMakeLists.txt
Previously we assumed it to be ecl (like the project name).
That is not correct. With this commit we now use the correct
default clone directory, libecl, in the sibling search.
> Use correct default clone directory in sibling search.

- CMakeLists.txt
- opm-parser-config.cmake.in
Previously, ecl_DIR was always set to the build directory used even
for the installed cmake configuration file. This patch at least allows
to overwrite that location and for the installed version tries to guess
the correct location. The guess is that libecl and opm-parser are installed
under the same prefix. As a fallback we use the package registry.
> Fix search path of libecl for installed opm-parser.

- lib/eclipse/include/opm/parser/eclipse/EclipseState/InitConfig/Equil.hpp
When running test in opm-parser, this never showed up as a problem since
Equil.hpp seems to be always included after <vector> is included (either
directly or by including other files). However, this can become a
problem when using opm-parser in other projects (eg, sunbeam)
If possible, this should backported to 2017.10/final. Alternatively, a workaround is to include <vector> before Equil.hpp whenever necessary
> Added missing include in Equil.hpp

- lib/eclipse/EclipseState/Eclipse3DProperties.cpp
- lib/eclipse/share/keywords/001_Eclipse300/T/THCGAS
- lib/eclipse/share/keywords/001_Eclipse300/T/THCOIL
- lib/eclipse/share/keywords/001_Eclipse300/T/THCROCK
- lib/eclipse/share/keywords/001_Eclipse300/T/THCWATER
- lib/eclipse/share/keywords/keyword_list.cmake
this is a small follow-up to #1158. It just adds the THC* keyword family to specify thermal conductivity. BTW: the approach of this keyword family is just a much too complicated way to set constant conductivity. That's because the final heat conductivity does not depend on the current solution at all, i.e. instead of just computing the arithmetic average of all fluid phases, it would be better to weight each phase conductivity with the phase's saturation.
> add more thermal keywords and the associated infrastructure

- lib/eclipse/EclipseState/Grid/GridProperty.cpp
this is another episode of the saga of energy support: E100 seems to silently use equil region zero if EQLNUM was not specified, and the data contained in the EQLNUM array uses fortran-style indices.
> fix the TEMPI property if it is initialized using RTEMPVD

- lib/eclipse/CMakeLists.txt
The test of the generated keywords had fallen out of cmake, re-inserting.
> Added generated keyword test.

- lib/eclipse/share/keywords/000_Eclipse100/W/WSEGSICD
- lib/eclipse/share/keywords/keyword_list.cmake
Adding the keywor WSEGSICD. 
The unit for the item 4 by definition is bar/(rm^3/day)^2 (METRIC), psi/(rft^3/day)^2 (FIELD)....
Since the `rft^3` is used for the FIELD unit system instead of `rb`, I use `Volume` for the `rm^3` and `rft^3` instead of `ReservoirVolume`. 
And also I have question about how to write this unit for the item 4. 
The confusion is from the definition of the keywords `COMPDAT`, the transmissibility factor unit is defined as `cP.rm^3 /day/bars` and the definition of the keyword is `Viscosity*ReservoirVolume/Time*Pressure`  instead of `Viscosity*ReservoirVolume/Time/Pressure`. It is something we have been using for almost all the cases and it has been working well, while some explanation is required here about the unit rule of the keyword definition.
> adding keyword WSEGSICD

- lib/eclipse/EclipseState/Schedule/Schedule.cpp
- lib/eclipse/EclipseState/Schedule/WellProductionProperties.cpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.hpp
- lib/eclipse/tests/WellTests.cpp
- lib/eclipse/tests/integration/ScheduleCreateFromDeck.cpp
This is the first part split from  https://github.com/OPM/opm-parser/pull/1168
We agreed to split that PR to make it easier to let it in, this is the first part. 
The major part is that for WCONHIST control production wells, they always have a BHP limit, and they can have another RATE limit instead of always having all the phase rate limits.
> Fixing history matching wells part 1

- lib/eclipse/tests/SummaryConfigTests.cpp
A compiler warning indicated a real, minor bug in SummaryConfigTests.cpp. However, the obvious fix leads to test failure.
I think you are better suited than me to decide what the correct test should be!
> [WIP] Minor fix for test program.

- lib/eclipse/Parser/ParseContext.cpp
- lib/eclipse/Parser/Parser.cpp
- lib/eclipse/include/opm/parser/eclipse/Parser/ParseContext.hpp
- lib/eclipse/tests/ParseContextTests.cpp
Adding a new keyword for handling reading of eclipse .DATA files. 
When reading a keyword whose length was specified in the previous keyword, an exception is thrown if there are more records than expected. 
With the new PARSE_EXTRA_RECORDS field, these extra records can be ignored.
> WIP: Added ParseContext::IGNORE_EXTRA_RECORDS

- lib/eclipse/CMakeLists.txt
- lib/eclipse/EclipseState/Eclipse3DProperties.cpp
- lib/eclipse/EclipseState/Grid/Box.cpp
- lib/eclipse/EclipseState/Grid/GridProperties.cpp
- lib/eclipse/EclipseState/Grid/setKeywordBox.cpp
- lib/eclipse/EclipseState/Grid/setKeywordBox.hpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Eclipse3DProperties.hpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Grid/Box.hpp
- lib/eclipse/tests/BoxTests.cpp
- lib/eclipse/tests/Eclipse3DPropertiesTests.cpp
Allow the use use of defaults in the operational keywords like `ADD` and `MULTIPLY`:
This now works:
```
MULTIPLY
'PERMX' 0.25 * * * * 4 4 /
/
```
to multiply `PERMX`in layer 4 - previously '*' could not be used.
> Default box

- CMakeLists.txt
to aid use of a super project for opm, see https://github.com/OPM/opm-common/pull/321
> changed: use PROJECT_SOURCE_DIR insteady of CMAKE_SOURCE_DIR

- lib/eclipse/EclipseState/Tables/Tables.cpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Tables/SpecheatTable.hpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/Tables/SpecrockTable.hpp
even though the official documentation does not seem to specify whether the specified heat capacities of the SPECROCK and SPECHEAT keywords are for constant pressure or for constant volume, the implicitly seem to be for the latter: pressure dependent heat capacites cannot be specified, yet the enthalpy for an incompressible fluid *is* pressure dependent, so the specified heat capacities must be for constant volume and they specify the internal energy instead of the enthalpy.
this requires some downstream mop-up in opm-material. permission to merge the downstream PR with this one is hereby granted.
> rename c_p to c_v in specrock and specheat table classes

- lib/eclipse/Units/UnitSystem.cpp
- lib/eclipse/include/opm/parser/eclipse/Units/UnitSystem.hpp
- lib/eclipse/include/opm/parser/eclipse/Units/Units.hpp
- lib/eclipse/tests/UnitTests.cpp
this is another attempt for fixing the "measure" temperature conversion stuff after #1203 without causing a trainwreck.
I did not find any substantial mistakes in #1203, so maybe some downstream code tries to work around the missing offset and thus creates a wrong result (then the downstream code needs to be fixed), maybe the reference data needs to be updated, or both. Anyway, temperature conversion is now much more thoroughly tested...
> respect the fact that non-SI temperature may be offset from zero

- lib/eclipse/EclipseState/Schedule/Schedule.cpp
- lib/eclipse/tests/data/integration_tests/SCHEDULE/SCHEDULE_WELLS2
- lib/eclipse/tests/integration/ScheduleCreateFromDeck.cpp
it must be a limit to turn it off. The old implementation make it impossible to have a injector with only bhp control.
And also, in my understanding, for well control, it always is the time or TSTEP after the `WCON*` keywords. Please correct me if I am wrong. I saw things very differently test cases many times and I always got confused.
> not turning off injector because of defaulted rates.

- lib/eclipse/EclipseState/AquiferCT.cpp
- lib/eclipse/include/opm/parser/eclipse/EclipseState/AquiferCT.hpp
Another minor warning squashing: unlike returning const references, returning const values is no different from returning a non-const value.
> Silence warning.

- lib/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- lib/eclipse/Parser/ParseContext.cpp
- lib/eclipse/include/opm/parser/eclipse/Parser/ParseContext.hpp
- lib/eclipse/tests/ParseContextTests.cpp
- lib/eclipse/tests/SummaryConfigTests.cpp
Will handle keywords like:
```
WWCT
/
```
in the summary section without complaining - even for decks without wells.
Observe that the second commit implies policy change, now the default behaviour for error condition `SUMMARY_UNKNOWN_WELL`is to completely ignore it. This is a policy change, the behaviour with respect to the
```
WWCT
/
``` 
configuration does *not* require this change of policy.
> Summary missing wells

- CMakeLists.txt
- CMakeLists_files.cmake
- ExtraTests.cmake
- GenerateKeywords.cmake
- debian/control
- debian/libopm-parser1-dev.install
This removes the opmjson library, instead opting for compiling the sources twice (one for generator, one for main library). less hassle.
the second commit fixes debian packaging and thus restores nightly builds.
> Remove json library
